# Generated by Django 5.2.9 on 2026-01-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('product_view', 'Product View'), ('search', 'Search'), ('booking_created', 'Booking Created'), ('booking_completed', 'Booking Completed'), ('user_registration', 'User Registration'), ('cart_add', 'Cart Add'), ('cart_remove', 'Cart Remove'), ('checkout_started', 'Checkout Started'), ('conversion', 'Conversion'), ('other', 'Other')], max_length=30, verbose_name='event type')),
                ('session_id', models.CharField(blank=True, max_length=100, verbose_name='session ID')),
                ('event_data', models.JSONField(blank=True, default=dict, help_text='Additional event-specific data', verbose_name='event data')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('referrer', models.URLField(blank=True, verbose_name='referrer')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
            ],
            options={
                'verbose_name': 'Analytics Event',
                'verbose_name_plural': 'Analytics Events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DailyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='date')),
                ('new_users', models.IntegerField(default=0, verbose_name='new users')),
                ('active_users', models.IntegerField(default=0, verbose_name='active users')),
                ('total_users', models.IntegerField(default=0, verbose_name='total users')),
                ('bookings_created', models.IntegerField(default=0, verbose_name='bookings created')),
                ('bookings_completed', models.IntegerField(default=0, verbose_name='bookings completed')),
                ('bookings_cancelled', models.IntegerField(default=0, verbose_name='bookings cancelled')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total revenue')),
                ('average_booking_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='average booking value')),
                ('products_viewed', models.IntegerField(default=0, verbose_name='products viewed')),
                ('unique_products_viewed', models.IntegerField(default=0, verbose_name='unique products viewed')),
                ('total_searches', models.IntegerField(default=0, verbose_name='total searches')),
                ('unique_searches', models.IntegerField(default=0, verbose_name='unique searches')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Daily Analytics',
                'verbose_name_plural': 'Daily Analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProductAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_views', models.IntegerField(default=0, verbose_name='total views')),
                ('unique_views', models.IntegerField(default=0, verbose_name='unique views')),
                ('total_searches', models.IntegerField(default=0, verbose_name='total searches')),
                ('total_cart_adds', models.IntegerField(default=0, verbose_name='total cart adds')),
                ('total_bookings', models.IntegerField(default=0, verbose_name='total bookings')),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0, help_text='Percentage of views that resulted in bookings', max_digits=5, verbose_name='conversion rate')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total revenue')),
                ('last_viewed', models.DateTimeField(blank=True, null=True, verbose_name='last viewed')),
                ('last_booked', models.DateTimeField(blank=True, null=True, verbose_name='last booked')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Product Analytics',
                'verbose_name_plural': 'Product Analytics',
            },
        ),
        migrations.CreateModel(
            name='UserBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('total_sessions', models.IntegerField(default=0, verbose_name='total sessions')),
                ('total_page_views', models.IntegerField(default=0, verbose_name='total page views')),
                ('favorite_categories', models.JSONField(blank=True, default=list, verbose_name='favorite categories')),
                ('favorite_products', models.JSONField(blank=True, default=list, verbose_name='favorite products')),
                ('total_bookings', models.IntegerField(default=0, verbose_name='total bookings')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total spent')),
                ('average_booking_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='average booking value')),
                ('preferred_price_range', models.JSONField(blank=True, default=dict, verbose_name='preferred price range')),
                ('preferred_rental_duration', models.IntegerField(blank=True, null=True, verbose_name='preferred rental duration (days)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'User Behavior',
                'verbose_name_plural': 'User Behaviors',
            },
        ),
    ]
