# Generated by Django 6.0.1 on 2026-02-02 23:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_initial'),
        ('products', '0003_productvariant_wishlist_alter_category_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyticsevent',
            options={'ordering': ['-timestamp'], 'verbose_name': 'حدث التحليلات', 'verbose_name_plural': 'أحداث التحليلات'},
        ),
        migrations.AlterModelOptions(
            name='dailyanalytics',
            options={'ordering': ['-date'], 'verbose_name': 'التحليلات اليومية', 'verbose_name_plural': 'التحليلات اليومية'},
        ),
        migrations.AlterModelOptions(
            name='productanalytics',
            options={'verbose_name': 'تحليلات المنتج', 'verbose_name_plural': 'تحليلات المنتجات'},
        ),
        migrations.AlterModelOptions(
            name='userbehavior',
            options={'verbose_name': 'سلوك المستخدم', 'verbose_name_plural': 'سلوكيات المستخدمين'},
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='productanalytics',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='products.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='userbehavior',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_type', models.CharField(choices=[('product', 'Product Forecast'), ('category', 'Category Forecast'), ('seasonal', 'Seasonal Forecast'), ('trend', 'Trend Forecast')], max_length=20, verbose_name='forecast type')),
                ('forecast_start', models.DateField(verbose_name='forecast start')),
                ('forecast_end', models.DateField(verbose_name='forecast end')),
                ('forecast_date', models.DateField(auto_now_add=True, verbose_name='forecast date')),
                ('predicted_demand', models.IntegerField(default=0, verbose_name='predicted demand')),
                ('predicted_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='predicted revenue')),
                ('confidence_level', models.DecimalField(decimal_places=2, default=0, help_text='Confidence level percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='confidence level')),
                ('seasonal_factor', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='seasonal factor')),
                ('trend_factor', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='trend factor')),
                ('forecast_data', models.JSONField(blank=True, default=dict, verbose_name='forecast data')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='products.category', verbose_name='category')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='products.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'التوقع',
                'verbose_name_plural': 'التوقعات',
                'ordering': ['-forecast_date', '-forecast_start'],
                'indexes': [models.Index(fields=['forecast_type', 'forecast_start'], name='analytics_f_forecas_dcc9ea_idx'), models.Index(fields=['product', 'forecast_start'], name='analytics_f_product_ef33cb_idx'), models.Index(fields=['category', 'forecast_start'], name='analytics_f_categor_05c246_idx')],
            },
        ),
    ]
