# Generated by Django 5.1.2 on 2026-04-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_analyticsevent_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketIntelligence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intel_type', models.CharField(choices=[('social_trend', 'Social Trend'), ('regional_liquidity', 'Regional Liquidity'), ('competitor_signal', 'Competitor Signal'), ('cultural_pulse', 'Cultural Pulse')], max_length=30)),
                ('region', models.CharField(default='Algeria', max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('metrics', models.JSONField(default=dict, help_text="e.g. {'growth': 15, 'engagement': 80}")),
                ('source_platform', models.CharField(blank=True, max_length=50)),
                ('external_url', models.URLField(blank=True)),
                ('confidence_score', models.IntegerField(default=70, help_text='0-100 scale')),
                ('is_active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'إستخبارات السوق',
                'verbose_name_plural': 'إستخبارات السوق',
                'ordering': ['-timestamp'],
            },
        ),
    ]
