# Generated by Django 5.2.9 on 2026-01-02 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_type', models.CharField(choices=[('full', 'Full Refund'), ('partial', 'Partial Refund'), ('damage_fee', 'Damage Fee Deduction'), ('late_fee', 'Late Fee Deduction')], max_length=20, verbose_name='refund type')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Refund amount (negative for charges)', max_digits=10, verbose_name='amount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('processed', 'Processed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status')),
                ('reason', models.TextField(verbose_name='reason')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
                ('transaction_reference', models.CharField(blank=True, help_text='Payment gateway transaction reference', max_length=100, verbose_name='transaction reference')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Refund',
                'verbose_name_plural': 'Refunds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_returned', models.IntegerField(default=1, verbose_name='quantity returned')),
                ('condition', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('damaged', 'Damaged'), ('lost', 'Lost')], max_length=20, verbose_name='condition')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
            ],
            options={
                'verbose_name': 'Return Item',
                'verbose_name_plural': 'Return Items',
            },
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('scheduled', 'Scheduled for Pickup'), ('in_transit', 'In Transit'), ('received', 'Received'), ('inspecting', 'Under Inspection'), ('accepted', 'Accepted'), ('damaged', 'Damaged'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='requested', max_length=20, verbose_name='status')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='requested at')),
                ('scheduled_pickup_date', models.DateField(blank=True, null=True, verbose_name='scheduled pickup date')),
                ('actual_pickup_date', models.DateField(blank=True, null=True, verbose_name='actual pickup date')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='received at')),
                ('inspection_date', models.DateTimeField(blank=True, null=True, verbose_name='inspection date')),
                ('inspection_notes', models.TextField(blank=True, verbose_name='inspection notes')),
                ('damage_assessment', models.TextField(blank=True, verbose_name='damage assessment')),
                ('damage_cost', models.DecimalField(decimal_places=2, default=0, help_text='Cost for any damages found', max_digits=10, verbose_name='damage cost')),
                ('return_notes', models.TextField(blank=True, verbose_name='return notes')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_request', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Return',
                'verbose_name_plural': 'Returns',
                'ordering': ['-requested_at'],
            },
        ),
    ]
