# Generated by Django 6.0.1 on 2026-02-02 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_options_alter_cart_options_and_more'),
        ('products', '0003_productvariant_wishlist_alter_category_options_and_more'),
        ('returns', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refund',
            options={'ordering': ['-created_at'], 'verbose_name': 'الاسترداد', 'verbose_name_plural': 'الاستردادات'},
        ),
        migrations.AlterModelOptions(
            name='return',
            options={'ordering': ['-requested_at'], 'verbose_name': 'الإرجاع', 'verbose_name_plural': 'الإرجاعات'},
        ),
        migrations.AlterModelOptions(
            name='returnitem',
            options={'verbose_name': 'عنصر الإرجاع', 'verbose_name_plural': 'عناصر الإرجاع'},
        ),
        migrations.AlterField(
            model_name='refund',
            name='return_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund', to='returns.return', verbose_name='return request'),
        ),
        migrations.AlterField(
            model_name='return',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_request', to='bookings.booking', verbose_name='booking'),
        ),
        migrations.AlterField(
            model_name='return',
            name='inspector',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['admin', 'staff']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_returns', to=settings.AUTH_USER_MODEL, verbose_name='inspector'),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='products.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='return_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='returns.return', verbose_name='return request'),
        ),
    ]
