# Generated by Django 5.2.9 on 2026-01-02 08:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock')], max_length=20, verbose_name='alert type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='pending', max_length=20, verbose_name='status')),
                ('message', models.TextField(verbose_name='message')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='acknowledged at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'Stock Alert',
                'verbose_name_plural': 'Stock Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out'), ('adjustment', 'Adjustment'), ('return', 'Return'), ('maintenance', 'Maintenance')], max_length=20, verbose_name='movement type')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantity')),
                ('previous_quantity', models.IntegerField(verbose_name='previous quantity')),
                ('new_quantity', models.IntegerField(verbose_name='new quantity')),
                ('reference_type', models.CharField(blank=True, help_text='Related model name (e.g., Booking, Return)', max_length=50, verbose_name='reference type')),
                ('reference_id', models.IntegerField(blank=True, help_text='Related object ID', null=True, verbose_name='reference ID')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_total', models.IntegerField(default=1, help_text='Total quantity available in inventory', validators=[django.core.validators.MinValueValidator(0)], verbose_name='total quantity')),
                ('quantity_available', models.IntegerField(default=1, help_text='Quantity currently available for rent', validators=[django.core.validators.MinValueValidator(0)], verbose_name='available quantity')),
                ('quantity_rented', models.IntegerField(default=0, help_text='Quantity currently rented', validators=[django.core.validators.MinValueValidator(0)], verbose_name='rented quantity')),
                ('quantity_maintenance', models.IntegerField(default=0, help_text='Quantity under maintenance', validators=[django.core.validators.MinValueValidator(0)], verbose_name='maintenance quantity')),
                ('low_stock_threshold', models.IntegerField(default=1, help_text='Alert when available quantity falls below this', validators=[django.core.validators.MinValueValidator(0)], verbose_name='low stock threshold')),
                ('last_restocked', models.DateTimeField(blank=True, null=True, verbose_name='last restocked')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_item', to='products.product')),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
            },
        ),
    ]
