# Generated by Django 6.0.1 on 2026-02-02 23:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        ('products', '0003_productvariant_wishlist_alter_category_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'verbose_name': 'عنصر المخزون', 'verbose_name_plural': 'عناصر المخزون'},
        ),
        migrations.AlterModelOptions(
            name='stockalert',
            options={'ordering': ['-created_at'], 'verbose_name': 'تنبيه المخزون', 'verbose_name_plural': 'تنبيهات المخزون'},
        ),
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-created_at'], 'verbose_name': 'حركة المخزون', 'verbose_name_plural': 'حركات المخزون'},
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_item', to='products.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='stockalert',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL, verbose_name='acknowledged_by'),
        ),
        migrations.AlterField(
            model_name='stockalert',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='inventory.inventoryitem', verbose_name='inventory_item'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.inventoryitem', verbose_name='inventory_item'),
        ),
        migrations.CreateModel(
            name='VariantInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_total', models.IntegerField(default=1, help_text='Total quantity available in inventory', validators=[django.core.validators.MinValueValidator(0)], verbose_name='total quantity')),
                ('quantity_available', models.IntegerField(default=1, help_text='Quantity currently available for rent', validators=[django.core.validators.MinValueValidator(0)], verbose_name='available quantity')),
                ('quantity_rented', models.IntegerField(default=0, help_text='Quantity currently rented', validators=[django.core.validators.MinValueValidator(0)], verbose_name='rented quantity')),
                ('quantity_maintenance', models.IntegerField(default=0, help_text='Quantity under maintenance', validators=[django.core.validators.MinValueValidator(0)], verbose_name='maintenance quantity')),
                ('low_stock_threshold', models.IntegerField(default=1, help_text='Alert when available quantity falls below this', validators=[django.core.validators.MinValueValidator(0)], verbose_name='low stock threshold')),
                ('last_restocked', models.DateTimeField(blank=True, null=True, verbose_name='last restocked')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='products.productvariant', verbose_name='variant')),
            ],
            options={
                'verbose_name': 'مخزون المتغير',
                'verbose_name_plural': 'مخزونات المتغيرات',
                'indexes': [models.Index(fields=['quantity_available'], name='inventory_v_quantit_672896_idx'), models.Index(fields=['variant', 'quantity_available'], name='inventory_v_variant_ebe228_idx')],
            },
        ),
    ]
