# Generated by Django 6.0.1 on 2026-02-02 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
        ('products', '0003_productvariant_wishlist_alter_category_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at'], 'verbose_name': 'الحجز', 'verbose_name_plural': 'الحجوزات'},
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'عربة التسوق', 'verbose_name_plural': 'عربات التسوق'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'عنصر العربة', 'verbose_name_plural': 'عناصر العربة'},
        ),
        migrations.AlterModelOptions(
            name='waitlist',
            options={'ordering': ['created_at'], 'verbose_name': 'قائمة الانتظار', 'verbose_name_plural': 'قوائم الانتظار'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='products.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bookings.cart', verbose_name='cart'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_items', to='products.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_items', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.CreateModel(
            name='DamageAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('none', 'No Damage'), ('minor', 'Minor Damage'), ('moderate', 'Moderate Damage'), ('severe', 'Severe Damage'), ('total', 'Total Loss')], default='none', max_length=20, verbose_name='severity')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('disputed', 'Disputed'), ('resolved', 'Resolved')], default='pending', max_length=20, verbose_name='status')),
                ('damage_description', models.TextField(blank=True, verbose_name='damage description')),
                ('repair_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='repair cost')),
                ('replacement_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='replacement cost')),
                ('assessed_at', models.DateTimeField(auto_now_add=True, verbose_name='assessed at')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments_made', to=settings.AUTH_USER_MODEL, verbose_name='assessed_by')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='damage_assessment', to='bookings.booking', verbose_name='booking')),
            ],
            options={
                'verbose_name': 'تقييم الأضرار',
                'verbose_name_plural': 'تقييمات الأضرار',
                'ordering': ['-assessed_at'],
            },
        ),
        migrations.CreateModel(
            name='DamageClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='claimed amount')),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='approved amount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='pending', max_length=20, verbose_name='status')),
                ('claim_description', models.TextField(verbose_name='claim description')),
                ('admin_notes', models.TextField(blank=True, verbose_name='admin notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolved at')),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='claim', to='bookings.damageassessment', verbose_name='assessment')),
            ],
            options={
                'verbose_name': 'مطالبة الضرر',
                'verbose_name_plural': 'مطالبات الأضرار',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DamagePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='damage_photos/', verbose_name='photo')),
                ('photo_type', models.CharField(choices=[('pre_rental', 'Pre-Rental'), ('post_rental', 'Post-Rental'), ('damage', 'Damage Detail'), ('repair', 'Repair Documentation')], max_length=20, verbose_name='photo type')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='bookings.damageassessment', verbose_name='assessment')),
            ],
            options={
                'verbose_name': 'صورة الضرر',
                'verbose_name_plural': 'صور الأضرار',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, verbose_name='item name')),
                ('item_description', models.TextField(blank=True, verbose_name='item description')),
                ('is_checked', models.BooleanField(default=False, verbose_name='checked')),
                ('condition', models.CharField(blank=True, max_length=50, verbose_name='condition')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='checked at')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='bookings.damageassessment', verbose_name='assessment')),
            ],
            options={
                'verbose_name': 'عنصر قائمة الفحص',
                'verbose_name_plural': 'عناصر قائمة الفحص',
                'ordering': ['item_name'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('reason', models.CharField(max_length=200, verbose_name='reason')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='status')),
                ('processing_days', models.IntegerField(default=3, verbose_name='processing days')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='transaction id')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='bookings.booking', verbose_name='booking')),
            ],
            options={
                'verbose_name': 'الاسترداد',
                'verbose_name_plural': 'الاستردادات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, verbose_name='reason')),
                ('cancellation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cancellation fee')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='refund amount')),
                ('cancelled_at', models.DateTimeField(auto_now_add=True, verbose_name='cancelled at')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation', to='bookings.booking', verbose_name='booking')),
                ('cancelled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancellations_made', to=settings.AUTH_USER_MODEL, verbose_name='cancelled_by')),
                ('refund', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancellation', to='bookings.refund', verbose_name='refund')),
            ],
            options={
                'verbose_name': 'الإلغاء',
                'verbose_name_plural': 'الإلغاءات',
                'ordering': ['-cancelled_at'],
            },
        ),
    ]
