# Generated by Django 6.0.1 on 2026-02-03 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_options_alter_cart_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='beneficiary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_escrows', to=settings.AUTH_USER_MODEL, verbose_name='المستفيد من الصرف'),
        ),
        migrations.AddField(
            model_name='booking',
            name='escrow_status',
            field=models.CharField(choices=[('INITIATED', 'تم الشروع'), ('HELD', 'محجوز في الخزنة'), ('RELEASED', 'تم الصرف'), ('REFUNDED', 'مسترجع')], default='HELD', max_length=20, verbose_name='حالة الاحتجاز'),
        ),
        migrations.AddField(
            model_name='booking',
            name='vault_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان الخزنة الرقمية'),
        ),
    ]
