# Generated by Django 6.0.1 on 2026-02-03 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_beneficiary_booking_escrow_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='agreements/audio/', verbose_name='ملف الصوت')),
                ('raw_text', models.TextField(blank=True, verbose_name='النص الخام (من الصوت أو الكتابة)')),
                ('contract_text', models.TextField(verbose_name='نص العقد القانوني')),
                ('structured_terms', models.JSONField(default=dict, verbose_name='الشروط المهيكلة (JSON)')),
                ('is_signed_by_user', models.BooleanField(default=False, verbose_name='توقيع المستأجر')),
                ('is_signed_by_owner', models.BooleanField(default=False, verbose_name='توقيع المؤجر')),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='smart_agreement', to='bookings.booking', verbose_name='booking')),
            ],
        ),
    ]
