# Generated by Django 6.0.1 on 2026-02-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_smartagreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='qr_code_token',
            field=models.TextField(blank=True, help_text='Cryptographic proof for offline verification', verbose_name='QR Token'),
        ),
    ]
