# Generated by Django 6.0.1 on 2026-02-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_qr_code_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='idempotency_key',
            field=models.UUIDField(blank=True, help_text='Unique key to prevent duplicate booking processing', null=True, unique=True),
        ),
    ]
