# Generated by Django 6.0.1 on 2026-02-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_idempotency_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='signature_proof',
            field=models.TextField(blank=True, help_text='Base64 Digital Signature', verbose_name='Signature Proof'),
        ),
        migrations.AddField(
            model_name='booking',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Signed At'),
        ),
    ]
