# Generated by Django 6.0.1 on 2026-02-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_booking_signature_proof_booking_signed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='base price'),
        ),
        migrations.AddField(
            model_name='booking',
            name='protection_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='protection fee'),
        ),
    ]
