# Generated by Django 6.0.1 on 2026-02-05 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_booking_base_price_booking_protection_fee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerticalReadinessAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vertical_slug', models.CharField(max_length=50, verbose_name='Vertical Slug')),
                ('role', models.CharField(choices=[('technical', 'Technical Guardian'), ('legal', 'Legal Guardian')], max_length=20, verbose_name='Guardian Role')),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, verbose_name='Audit Notes')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sovereign_signoffs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sovereign Sign-off',
                'verbose_name_plural': 'Vertical Readiness Council',
                'unique_together': {('vertical_slug', 'role')},
            },
        ),
    ]
