# Generated by Django 5.2.9 on 2026-02-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_verticalreadinessaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='security deposit'),
        ),
    ]
