# Generated by Django 6.0.3 on 2026-03-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_booking_security_deposit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='escrow_status',
        ),
        migrations.AddField(
            model_name='booking',
            name='_escrow_status_db',
            field=models.CharField(choices=[('INITIATED', 'تم الشروع'), ('HELD', 'محجوز في الخزنة'), ('RELEASED', 'تم الصرف'), ('REFUNDED', 'مسترجع'), ('DISPUTED', 'قيد النزاع'), ('SPLIT_RELEASED', 'صرف مقسّم')], db_column='escrow_status', default='HELD', editable=False, max_length=20, verbose_name='حالة الاحتجاز (legacy cache)'),
        ),
    ]
