# Generated by Django 5.1.2 on 2026-04-01 06:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_remove_booking_escrow_status_and_more'),
        ('products', '0011_alter_productvariant_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_product_52e748_idx',
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['product', 'status'], name='bookings_bo_product_04aaea_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['start_date', 'end_date'], name='bookings_bo_start_d_8ecf7f_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['idempotency_key'], name='bookings_bo_idempot_c34e90_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='booking_end_date_after_start_date'),
        ),
    ]
