# Generated by Django 5.1.2 on 2026-04-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_remove_booking_bookings_bo_product_52e748_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='booking_end_date_after_start_date',
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(
                condition=models.Q(('end_date__gte', models.F('start_date'))),
                name='booking_end_date_after_start_date',
            ),
        ),
    ]
