# Generated by Django 5.1.2 on 2026-04-06 18:59

import apps.bookings.models
import django.contrib.postgres.constraints
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_alter_booking_same_day_allowed'),
        ('products', '0013_alter_product_price_per_day'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_use', 'In Use'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('manual_review', 'Under Manual Review'), ('rejected', 'Rejected (Risk Policy)')], default='pending', max_length=20, verbose_name='status'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ['confirmed', 'in_use'])), expressions=[('product', '='), (apps.bookings.models.DateRange('start_date', 'end_date', models.Value('[)')), '&&')], name='exclude_overlapping_bookings'),
        ),
    ]
