# Generated by Django 6.0.1 on 2026-02-03 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vouch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouches_received', to=settings.AUTH_USER_MODEL, verbose_name='Receiver')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers_given', to=settings.AUTH_USER_MODEL, verbose_name='Voucher')),
            ],
            options={
                'verbose_name': 'تزكية',
                'verbose_name_plural': 'تزكيات',
                'unique_together': {('voucher', 'receiver')},
            },
        ),
    ]
