# Generated by Django 6.0.1 on 2026-02-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouch',
            name='relationship',
            field=models.CharField(choices=[('family', 'Family'), ('friend', 'Friend'), ('colleague', 'Colleague'), ('neighbor', 'Neighbor'), ('community', 'Community Member')], default='community', max_length=20, verbose_name='relationship'),
        ),
        migrations.AddField(
            model_name='vouch',
            name='trust_level',
            field=models.IntegerField(choices=[(1, 'I know them'), (2, 'I trust them'), (3, 'I highly trust them'), (4, 'I guarantee for them'), (5, 'Relative / Inner Circle')], default=1, verbose_name='trust level'),
        ),
    ]
