# Generated by Django 6.0.1 on 2026-02-05 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_vouch_relationship_vouch_trust_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(blank=True, max_length=50, verbose_name='Referral Code')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('revoked', 'Revoked (Penalty Applied)')], default='pending', max_length=20)),
                ('social_collateral', models.IntegerField(default=20, help_text='Points deducted from Parent if Child is blacklisted.', verbose_name='Social Collateral')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_received', to=settings.AUTH_USER_MODEL, verbose_name='Referred (Child)')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_sent', to=settings.AUTH_USER_MODEL, verbose_name='Referrer (Parent)')),
            ],
            options={
                'verbose_name': 'الإحالة',
                'verbose_name_plural': 'الإحالات',
                'ordering': ['-created_at'],
            },
        ),
    ]
