# Generated by Django 5.2.9 on 2026-01-02 08:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarrantyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('name_ar', models.CharField(max_length=100, verbose_name='name (Arabic)')),
                ('plan_type', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium'), ('full_coverage', 'Full Coverage')], max_length=20, verbose_name='plan type')),
                ('coverage_type', models.CharField(choices=[('damage', 'Damage Protection'), ('theft', 'Theft Protection'), ('loss', 'Loss Protection'), ('full', 'Full Coverage')], max_length=20, verbose_name='coverage type')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('description_ar', models.TextField(blank=True, verbose_name='description (Arabic)')),
                ('price', models.DecimalField(decimal_places=2, help_text='Warranty price per rental', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price')),
                ('price_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage of rental price (alternative to fixed price)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='price percentage')),
                ('max_coverage_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum amount covered by warranty', max_digits=10, null=True, verbose_name='maximum coverage amount')),
                ('deductible', models.DecimalField(decimal_places=2, default=0, help_text='Amount customer pays before warranty kicks in', max_digits=10, verbose_name='deductible')),
                ('covers_normal_wear', models.BooleanField(default=False, verbose_name='covers normal wear')),
                ('covers_accidental_damage', models.BooleanField(default=True, verbose_name='covers accidental damage')),
                ('covers_theft', models.BooleanField(default=False, verbose_name='covers theft')),
                ('covers_loss', models.BooleanField(default=False, verbose_name='covers loss')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Warranty Plan',
                'verbose_name_plural': 'Warranty Plans',
                'ordering': ['plan_type', 'price'],
                'indexes': [models.Index(fields=['is_active', 'is_featured'], name='warranties__is_acti_e386a0_idx')],
            },
        ),
        migrations.CreateModel(
            name='WarrantyPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warranty_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='warranty price')),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='coverage amount')),
                ('deductible', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='deductible')),
                ('status', models.CharField(choices=[('active', 'Active'), ('claimed', 'Claimed'), ('expired', 'Expired'), ('void', 'Void')], default='active', max_length=20, verbose_name='status')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='purchased at')),
                ('activated_at', models.DateTimeField(auto_now_add=True, verbose_name='activated at')),
                ('expires_at', models.DateTimeField(verbose_name='expires at')),
                ('claimed_at', models.DateTimeField(blank=True, null=True, verbose_name='claimed at')),
                ('claim_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='claim amount')),
                ('claim_description', models.TextField(blank=True, verbose_name='claim description')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warranty', to='bookings.booking')),
                ('warranty_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='warranties.warrantyplan')),
            ],
            options={
                'verbose_name': 'Warranty Purchase',
                'verbose_name_plural': 'Warranty Purchases',
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.CreateModel(
            name='WarrantyClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_type', models.CharField(choices=[('damage', 'Damage'), ('theft', 'Theft'), ('loss', 'Loss'), ('other', 'Other')], max_length=20, verbose_name='claim type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='pending', max_length=20, verbose_name='status')),
                ('claim_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='claim amount')),
                ('description', models.TextField(verbose_name='description')),
                ('evidence_files', models.JSONField(blank=True, default=list, help_text='List of file URLs or paths', verbose_name='evidence files')),
                ('review_notes', models.TextField(blank=True, verbose_name='review notes')),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='approved amount')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='submitted at')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='paid at')),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['admin', 'staff']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_warranty_claims', to=settings.AUTH_USER_MODEL)),
                ('warranty_purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='warranties.warrantypurchase')),
            ],
            options={
                'verbose_name': 'Warranty Claim',
                'verbose_name_plural': 'Warranty Claims',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='warrantypurchase',
            index=models.Index(fields=['booking', 'status'], name='warranties__booking_527104_idx'),
        ),
        migrations.AddIndex(
            model_name='warrantypurchase',
            index=models.Index(fields=['status', 'expires_at'], name='warranties__status_7160bc_idx'),
        ),
        migrations.AddIndex(
            model_name='warrantyclaim',
            index=models.Index(fields=['status', 'submitted_at'], name='warranties__status_fdeb72_idx'),
        ),
    ]
