# Generated by Django 6.0.1 on 2026-02-02 23:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_options_alter_cart_options_and_more'),
        ('warranties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('name_ar', models.CharField(max_length=100, verbose_name='name (Arabic)')),
                ('plan_type', models.CharField(choices=[('basic', 'Basic Insurance'), ('premium', 'Premium Insurance'), ('full_coverage', 'Full Coverage Insurance')], max_length=20, verbose_name='plan type')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('description_ar', models.TextField(blank=True, verbose_name='description (Arabic)')),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='base price')),
                ('price_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage of product value', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='price percentage')),
                ('max_coverage_percentage', models.DecimalField(decimal_places=2, default=100, help_text='Maximum coverage as percentage of product value', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='max coverage percentage')),
                ('deductible_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Deductible as percentage of claim amount', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='deductible percentage')),
                ('covers_damage', models.BooleanField(default=True, verbose_name='covers damage')),
                ('covers_theft', models.BooleanField(default=False, verbose_name='covers theft')),
                ('covers_loss', models.BooleanField(default=False, verbose_name='covers loss')),
                ('covers_accidental_damage', models.BooleanField(default=True, verbose_name='covers accidental damage')),
                ('covers_normal_wear', models.BooleanField(default=False, verbose_name='covers normal wear')),
                ('applicable_product_types', models.JSONField(blank=True, default=list, help_text='List of product category IDs this plan applies to (empty = all)', verbose_name='applicable product types')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'خطة التأمين',
                'verbose_name_plural': 'خطط التأمين',
                'ordering': ['plan_type', 'base_price'],
            },
        ),
        migrations.AlterModelOptions(
            name='warrantyclaim',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'مطالبة الضمان', 'verbose_name_plural': 'مطالبات الضمان'},
        ),
        migrations.AlterModelOptions(
            name='warrantyplan',
            options={'ordering': ['plan_type', 'price'], 'verbose_name': 'خطة الضمان', 'verbose_name_plural': 'خطط الضمان'},
        ),
        migrations.AlterModelOptions(
            name='warrantypurchase',
            options={'ordering': ['-purchased_at'], 'verbose_name': 'شراء الضمان', 'verbose_name_plural': 'مشتريات الضمان'},
        ),
        migrations.AlterField(
            model_name='warrantyclaim',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['admin', 'staff']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_warranty_claims', to=settings.AUTH_USER_MODEL, verbose_name='reviewed_by'),
        ),
        migrations.AlterField(
            model_name='warrantyclaim',
            name='warranty_purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='warranties.warrantypurchase', verbose_name='warranty_purchase'),
        ),
        migrations.AlterField(
            model_name='warrantypurchase',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warranty', to='bookings.booking', verbose_name='booking'),
        ),
        migrations.AlterField(
            model_name='warrantypurchase',
            name='warranty_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='warranties.warrantyplan', verbose_name='warranty_plan'),
        ),
    ]
