# Generated by Django 6.0.1 on 2026-02-02 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '__first__'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'المستخدم', 'verbose_name_plural': 'المستخدمون'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'الملف الشخصي', 'verbose_name_plural': 'الملفات الشخصية'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='reason')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blacklist_additions', to=settings.AUTH_USER_MODEL, verbose_name='added_by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklist_entries', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'قائمة الحظر',
                'verbose_name_plural': 'قوائم الحظر',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='status')),
                ('id_type', models.CharField(blank=True, choices=[('national_id', 'National ID'), ('passport', 'Passport'), ('driver_license', 'Driver License')], max_length=20, verbose_name='ID type')),
                ('id_number', models.CharField(blank=True, max_length=50, verbose_name='ID number')),
                ('id_front_image', models.ImageField(blank=True, null=True, upload_to='verification/id_front/', verbose_name='ID front image')),
                ('id_back_image', models.ImageField(blank=True, null=True, upload_to='verification/id_back/', verbose_name='ID back image')),
                ('phone_verified', models.BooleanField(default=False, verbose_name='phone verified')),
                ('phone_verification_code', models.CharField(blank=True, max_length=10, verbose_name='phone verification code')),
                ('phone_verification_expires', models.DateTimeField(blank=True, null=True, verbose_name='phone verification expires')),
                ('address_verified', models.BooleanField(default=False, verbose_name='address verified')),
                ('risk_score', models.IntegerField(default=0, help_text='Risk score from 0-100', verbose_name='risk score')),
                ('is_blacklisted', models.BooleanField(default=False, verbose_name='blacklisted')),
                ('blacklist_reason', models.TextField(blank=True, verbose_name='blacklist reason')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verified at')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='rejection reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications_approved', to=settings.AUTH_USER_MODEL, verbose_name='verified_by')),
            ],
            options={
                'verbose_name': 'حالة التحقق',
                'verbose_name_plural': 'حالات التحقق',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('approve', 'Approve'), ('reject', 'Reject'), ('login', 'Login'), ('logout', 'Logout'), ('other', 'Other')], max_length=20, verbose_name='action')),
                ('model_name', models.CharField(max_length=100, verbose_name='model name')),
                ('object_id', models.IntegerField(blank=True, null=True, verbose_name='object ID')),
                ('description', models.TextField(verbose_name='description')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'سجل النشاط',
                'verbose_name_plural': 'سجلات النشاط',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='users_activ_user_id_f1f5e0_idx'), models.Index(fields=['action', 'created_at'], name='users_activ_action_92dc6d_idx'), models.Index(fields=['model_name', 'object_id'], name='users_activ_model_n_887e50_idx')],
            },
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_period_start', models.DateField(verbose_name='review period start')),
                ('review_period_end', models.DateField(verbose_name='review period end')),
                ('overall_rating', models.IntegerField(choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], verbose_name='overall rating')),
                ('punctuality_rating', models.IntegerField(choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], verbose_name='punctuality rating')),
                ('quality_rating', models.IntegerField(choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], verbose_name='quality rating')),
                ('communication_rating', models.IntegerField(choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], verbose_name='communication rating')),
                ('strengths', models.TextField(blank=True, verbose_name='strengths')),
                ('areas_for_improvement', models.TextField(blank=True, verbose_name='areas for improvement')),
                ('goals', models.TextField(blank=True, verbose_name='goals')),
                ('comments', models.TextField(blank=True, verbose_name='comments')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, verbose_name='reviewed at')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_conducted', to=settings.AUTH_USER_MODEL, verbose_name='reviewed_by')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to=settings.AUTH_USER_MODEL, verbose_name='staff')),
            ],
            options={
                'verbose_name': 'تقييم الأداء',
                'verbose_name_plural': 'تقييمات الأداء',
                'ordering': ['-reviewed_at'],
                'indexes': [models.Index(fields=['staff', 'reviewed_at'], name='users_perfo_staff_i_b4cc4a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField(verbose_name='shift date')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('is_completed', models.BooleanField(default=False, verbose_name='completed')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='branches.branch', verbose_name='branch')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to=settings.AUTH_USER_MODEL, verbose_name='staff')),
            ],
            options={
                'verbose_name': 'المناوبة',
                'verbose_name_plural': 'المناوبات',
                'ordering': ['shift_date', 'start_time'],
                'indexes': [models.Index(fields=['staff', 'shift_date'], name='users_shift_staff_i_9cd628_idx'), models.Index(fields=['branch', 'shift_date'], name='users_shift_branch__1fca26_idx')],
            },
        ),
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('staff', 'Staff'), ('delivery', 'Delivery Staff'), ('support', 'Support Staff')], max_length=20, verbose_name='role')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='department')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='assigned at')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments', to=settings.AUTH_USER_MODEL, verbose_name='assigned_by')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_role_assignments', to='branches.branch', verbose_name='branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_roles', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'دور الموظف',
                'verbose_name_plural': 'أدوار الموظفين',
                'ordering': ['-assigned_at'],
                'unique_together': {('user', 'role', 'branch')},
            },
        ),
    ]
