# Generated by Django 6.0.1 on 2026-02-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supabase_user_id',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='Supabase User ID'),
        ),
    ]
