# Generated by Django 6.0.1 on 2026-02-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_supabase_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationstatus',
            name='selfie',
            field=models.ImageField(blank=True, null=True, upload_to='verification/selfie/', verbose_name='selfie'),
        ),
    ]
