# Generated by Django 5.2.9 on 2026-02-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_verificationstatus_selfie'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='consecutive_emotional_attempts',
            field=models.IntegerField(default=0, verbose_name='consecutive emotional attempts'),
        ),
        migrations.AddField(
            model_name='user',
            name='emotional_lock_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='emotional lock until'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_dispute_attempt_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last dispute attempt'),
        ),
    ]
