# Generated by Django 5.2.9 on 2026-02-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_consecutive_emotional_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='merit_score',
            field=models.IntegerField(default=50, verbose_name='merit score'),
        ),
    ]
