# Generated by Django 5.2.9 on 2026-02-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_merit_score"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.AddField(
            model_name="user",
            name="email_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="HMAC-SHA256 of normalized email. Used for auth lookup.",
                max_length=88,
                verbose_name="email hash",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="HMAC-SHA256 of normalized phone. Used for OTP lookup.",
                max_length=88,
                verbose_name="phone hash",
            ),
        ),
    ]
