# Generated by Django 5.2.9 on 2026-02-18 14:52
# Manually edited: Phase 16A.1 — null existing empty hashes only

from django.db import migrations


def null_empty_hashes(apps, schema_editor):
    """
    NULL out empty string hashes.
    Required before any uniqueness enforcement on email_hash.
    Uses raw SQL via schema_editor to avoid ORM overhead.
    """
    schema_editor.execute(
        "UPDATE users_user SET email_hash = NULL WHERE email_hash = ''"
    )
    schema_editor.execute(
        "UPDATE users_user SET phone_hash = NULL WHERE phone_hash = ''"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0007_alter_user_managers_user_email_hash_user_phone_hash"),
    ]

    operations = [
        # NULL out existing empty strings so future uniqueness enforcement works.
        # Note: null=True is a model-level change only for this SQLite dev environment.
        # PostgreSQL production will enforce NOT NULL + partial unique index.
        migrations.RunPython(null_empty_hashes, reverse_code=migrations.RunPython.noop),
    ]
