# Generated by Django 5.2.9 on 2026-02-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_email_hash_constraint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="HMAC-SHA256 of normalized email. NULL until backfill. Used for auth lookup.",
                max_length=88,
                null=True,
                verbose_name="email hash",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="HMAC-SHA256 of normalized phone. NULL until backfill. Used for OTP lookup.",
                max_length=88,
                null=True,
                verbose_name="phone hash",
            ),
        ),
    ]
