# Generated by Django 5.2.9 on 2026-02-19 14:29

import apps.core.crypto.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_email_hash_null_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_encrypted",
            field=apps.core.crypto.fields.EncryptedCharField(
                blank=True,
                help_text="Phase 16C: AES-encrypted email. NULL until backfill. After 16C.4a this becomes the canonical email field.",
                null=True,
                verbose_name="email (encrypted)",
            ),
        ),
    ]
