# Generated by Django CTO Protocol to enforce strict schema invariants

import apps.core.crypto.fields  # type: ignore
from django.db import migrations  # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_phase_16c4b_drop_plaintext'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='user',
                    name='email_plaintext_backup',
                ),
            ],
            database_operations=[],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=apps.core.crypto.fields.EncryptedCharField(unique=True, verbose_name='email address'),
            # No default provided because the database should not have any NULL emails
            # at this point in the cutover phase. This enforces the constraint securely.
        ),
    ]
