# Generated by Django 5.1.2 on 2026-04-01 06:25

import apps.core.crypto.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_gap02_kyc_verification_level_face'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False, verbose_name='2FA Enabled'),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_secret',
            field=apps.core.crypto.fields.EncryptedCharField(blank=True, max_length=32, null=True, verbose_name='TOTP Secret'),
        ),
    ]
