# Generated by Django 5.1.2 on 2026-04-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_identitydocument_businessprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trust_score',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5, verbose_name='sovereign trust score'),
        ),
    ]
