# Generated by Django 6.0.1 on 2026-02-03 06:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0005_smartagreement'),
        ('products', '0004_product_is_community_approved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200, verbose_name='business name')),
                ('business_name_ar', models.CharField(max_length=200, verbose_name='business name (Arabic)')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='tax ID')),
                ('registration_number', models.CharField(blank=True, max_length=50, verbose_name='registration number')),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('address', models.TextField(verbose_name='address')),
                ('city', models.CharField(default='Constantine', max_length=100, verbose_name='city')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('description_ar', models.TextField(blank=True, verbose_name='description (Arabic)')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='vendors/logos/', verbose_name='logo')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=15.0, help_text='Commission percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='commission rate')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('suspended', 'Suspended'), ('inactive', 'Inactive')], default='pending', max_length=20, verbose_name='status')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verified at')),
                ('total_products', models.IntegerField(default=0, verbose_name='total products')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='total sales')),
                ('total_commission', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='total commission')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='rating')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_vendors', to=settings.AUTH_USER_MODEL, verbose_name='verified_by')),
            ],
            options={
                'verbose_name': 'المورد',
                'verbose_name_plural': 'الموردين',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='sale amount')),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='commission rate')),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='commission amount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('calculated', 'Calculated'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, verbose_name='calculated at')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='paid at')),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='payment reference')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_commissions', to='bookings.booking', verbose_name='booking')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='products.product', verbose_name='product')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='vendors.vendor', verbose_name='vendor')),
            ],
            options={
                'verbose_name': 'العمولة',
                'verbose_name_plural': 'العمولات',
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='period start')),
                ('period_end', models.DateField(verbose_name='period end')),
                ('total_bookings', models.IntegerField(default=0, verbose_name='total bookings')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='total revenue')),
                ('total_commission', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='total commission')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='average rating')),
                ('products_added', models.IntegerField(default=0, verbose_name='products added')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to='vendors.vendor', verbose_name='vendor')),
            ],
            options={
                'verbose_name': 'أداء المورد',
                'verbose_name_plural': 'أداءات الموردين',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='VendorProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Override vendor commission rate for this product', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='commission rate')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='added at')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_products', to='products.product', verbose_name='product')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='vendors.vendor', verbose_name='vendor')),
            ],
            options={
                'verbose_name': 'منتج المورد',
                'verbose_name_plural': 'منتجات الموردين',
                'ordering': ['-added_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['status', 'is_verified'], name='vendors_ven_status_b3c4a8_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['business_name'], name='vendors_ven_busines_c24d58_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['vendor', 'status'], name='vendors_com_vendor__2a9fe9_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['status', 'calculated_at'], name='vendors_com_status_79364a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vendorperformance',
            unique_together={('vendor', 'period_start', 'period_end')},
        ),
        migrations.AlterUniqueTogether(
            name='vendorproduct',
            unique_together={('vendor', 'product')},
        ),
    ]
