# Generated by Django 6.0.1 on 2026-02-05 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_verticalreadinessaudit'),
        ('disputes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='Event Action')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(default=dict, verbose_name='Event Metadata')),
                ('hash', models.CharField(blank=True, max_length=128, verbose_name='Integrity Hash')),
                ('context_snapshot', models.JSONField(default=dict, help_text='Versions of Policy, Contract, and Risk Engine at time of event.', verbose_name='Context Snapshot')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_logs', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_trail', to='bookings.booking')),
                ('dispute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_trail', to='disputes.dispute')),
            ],
            options={
                'verbose_name': 'سجل الأدلة',
                'verbose_name_plural': 'سجل الأدلة (The Vault)',
                'ordering': ['-timestamp'],
            },
        ),
    ]
