# Generated by Django 6.0.1 on 2026-02-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0002_evidencelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='admissibility_report',
            field=models.JSONField(blank=True, default=dict, verbose_name='Admissibility Report'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='inadmissible_reason',
            field=models.TextField(blank=True, verbose_name='Rejection Reason'),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='status',
            field=models.CharField(choices=[('filed', 'Filed (Pending Admissibility)'), ('admissible', 'Admissible (Discovery Open)'), ('inadmissible', 'Inadmissible (Rejected)'), ('under_review', 'Under Review (Deliberation)'), ('judgment_provisional', 'Judgment Provisional'), ('judgment_final', 'Judgment Final'), ('closed', 'Closed')], default='filed', max_length=50, verbose_name='status'),
        ),
    ]
