# Generated by Django 6.0.1 on 2026-02-05 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0003_dispute_admissibility_report_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Judgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(choices=[('favor_tenant', 'Favor Tenant'), ('favor_owner', 'Favor Owner'), ('split', 'Split Decision'), ('dismissed', 'Dismissed')], max_length=20, verbose_name='verdict')),
                ('ruling_text', models.TextField(verbose_name='ruling reasoning')),
                ('status', models.CharField(choices=[('provisional', 'Provisional (Appeal Window Open)'), ('final', 'Final (Enforceable)'), ('overturned', 'Overturned (Void)')], default='provisional', max_length=20, verbose_name='status')),
                ('awarded_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Awarded Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('finalized_at', models.DateTimeField(blank=True, null=True, verbose_name='finalized at')),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judgments', to='disputes.dispute', verbose_name='dispute')),
                ('judge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='judgments_authored', to=settings.AUTH_USER_MODEL, verbose_name='judge')),
            ],
            options={
                'verbose_name': 'الحكم',
                'verbose_name_plural': 'الأحكام',
                'ordering': ['-created_at'],
            },
        ),
    ]
