# Generated by Django 6.0.1 on 2026-02-05 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0004_judgment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Why is the judgment flawed?', verbose_name='reason for appeal')),
                ('bond_reference', models.CharField(blank=True, help_text='Proof of skin in the game', max_length=100, verbose_name='Bond Reference')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('granted', 'Granted (Judgment Overturned/Remanded)'), ('rejected', 'Rejected (Judgment Finalized)')], default='pending', max_length=20, verbose_name='status')),
                ('review_notes', models.TextField(blank=True, verbose_name='review notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('appellant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals_filed', to=settings.AUTH_USER_MODEL, verbose_name='appellant')),
                ('judgment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appeal', to='disputes.judgment', verbose_name='judgment')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeals_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='high court judge')),
            ],
            options={
                'verbose_name': 'الاستئناف',
                'verbose_name_plural': 'الاستئنافات',
                'ordering': ['-created_at'],
            },
        ),
    ]
