# Generated by Django 6.0.1 on 2026-02-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0005_appeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='is_fund_frozen',
            field=models.BooleanField(default=True, help_text='Escrow execution is blocked while pending.', verbose_name='Funds Frozen?'),
        ),
    ]
