# Generated by Django 6.0.1 on 2026-02-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0006_appeal_is_fund_frozen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='bond_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bond Reference'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('granted', 'Granted (Judgment Overturned)'), ('rejected', 'Rejected (Judgment Finalized)'), ('remanded', 'Remanded (Sent back to Tribunal)')], default='pending', max_length=20, verbose_name='status'),
        ),
    ]
