# Generated by Django 6.0.1 on 2026-02-05 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0007_alter_appeal_bond_reference_alter_appeal_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgmentPrecedent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(help_text='0.0 to 1.0 - How similar are the disputes?', verbose_name='Similarity Score')),
                ('was_followed', models.BooleanField(default=True, help_text='Did current judgment align with precedent verdict?', verbose_name='Was Followed?')),
                ('divergence_reason', models.TextField(blank=True, help_text='Why did we diverge from this precedent?', verbose_name='Divergence Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='linked at')),
                ('judgment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precedents_used', to='disputes.judgment', verbose_name='current judgment')),
                ('precedent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precedents_cited', to='disputes.judgment', verbose_name='historical precedent')),
            ],
            options={
                'verbose_name': 'سابقة قضائية',
                'verbose_name_plural': 'السوابق القضائية',
                'ordering': ['-created_at'],
                'unique_together': {('judgment', 'precedent')},
            },
        ),
    ]
