# Generated by Django 6.0.1 on 2026-02-05 22:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0008_judgmentprecedent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JudicialPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., "Damage Review Panel", "Timeliness Panel"', max_length=100, verbose_name='Panel Name')),
                ('panel_type', models.CharField(choices=[('routine', 'Routine Cases'), ('specialized', 'Specialized Domain'), ('high_court', 'High Court')], default='routine', max_length=20, verbose_name='Panel Type')),
                ('description', models.TextField(help_text='What types of cases does this panel handle?', verbose_name='Description')),
                ('max_cases_per_week', models.IntegerField(default=10, help_text='Maximum active cases this panel can handle', verbose_name='Weekly Capacity')),
                ('current_load', models.IntegerField(default=0, help_text='Number of currently active cases', verbose_name='Current Load')),
                ('rotation_date', models.DateField(blank=True, help_text='When panel members were last rotated', null=True, verbose_name='Last Rotation')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('members', models.ManyToManyField(blank=True, related_name='judicial_panels', to=settings.AUTH_USER_MODEL, verbose_name='Panel Members')),
            ],
            options={
                'verbose_name': 'لجنة قضائية',
                'verbose_name_plural': 'اللجان القضائية',
                'ordering': ['name'],
            },
        ),
    ]
