# Generated by Django 6.0.1 on 2026-02-06 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0009_judicialpanel'),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgmentEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_vector', models.JSONField(help_text='Normalized text embedding for semantic search', verbose_name='embedding vector')),
                ('model_version', models.CharField(default='paraphrase-multilingual-MiniLM-L12-v2', help_text='Embedding model used to generate this vector', max_length=100, verbose_name='model version')),
                ('original_text', models.TextField(help_text='Original judgment text (for display)', verbose_name='original text')),
                ('normalized_text', models.TextField(help_text='Normalized text used for embedding (Arabic cleaned)', verbose_name='normalized text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('judgment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='disputes.judgment', verbose_name='judgment')),
            ],
            options={
                'verbose_name': 'judgment embedding',
                'verbose_name_plural': 'judgment embeddings',
                'db_table': 'disputes_judgment_embedding',
                'indexes': [models.Index(fields=['created_at'], name='disputes_ju_created_2c2c1f_idx'), models.Index(fields=['model_version'], name='disputes_ju_model_v_2b9049_idx')],
            },
        ),
    ]
