# Generated by Django 6.0.1 on 2026-02-06 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0010_judgmentembedding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymizedJudgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judgment_hash', models.CharField(help_text='SHA256(judgment.id + salt)', max_length=64, unique=True, verbose_name='judgment hash')),
                ('category', models.CharField(db_index=True, max_length=100, verbose_name='category')),
                ('dispute_type', models.CharField(max_length=200, verbose_name='dispute type')),
                ('ruling_summary', models.TextField(help_text='AI-generated, stripped of names/locations', verbose_name='ruling summary')),
                ('verdict', models.CharField(db_index=True, max_length=20, verbose_name='verdict')),
                ('awarded_ratio', models.DecimalField(blank=True, decimal_places=2, help_text='May be redacted for privacy', max_digits=5, null=True, verbose_name='awarded ratio %')),
                ('evidence_types', models.JSONField(default=list, help_text='["photo", "contract", "witness"]', verbose_name='evidence types')),
                ('consistency_score', models.IntegerField(default=0, help_text='0-100, from precedent search', verbose_name='consistency score')),
                ('similar_cases_count', models.IntegerField(default=0, verbose_name='similar cases count')),
                ('judgment_date', models.DateField(db_index=True, help_text='Month precision only (day=1)', verbose_name='judgment date')),
                ('geographic_region', models.CharField(blank=True, help_text='Province level, may be redacted', max_length=100, null=True, verbose_name='geographic region')),
                ('uniqueness_score', models.IntegerField(default=0, help_text='0-100, higher = more unique/identifiable', verbose_name='uniqueness score')),
                ('publication_delayed_until', models.DateField(blank=True, help_text='For high-risk categories', null=True, verbose_name='publication delayed until')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='published at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'anonymized judgment',
                'verbose_name_plural': 'anonymized judgments',
                'db_table': 'disputes_anonymized_judgment',
                'ordering': ['-judgment_date'],
                'indexes': [models.Index(fields=['category', 'verdict'], name='disputes_an_categor_8a9acb_idx'), models.Index(fields=['consistency_score'], name='disputes_an_consist_addea1_idx'), models.Index(fields=['judgment_date'], name='disputes_an_judgmen_887108_idx'), models.Index(fields=['uniqueness_score'], name='disputes_an_uniquen_394f24_idx')],
            },
        ),
        migrations.CreateModel(
            name='PostJudgmentSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('understands_decision', models.BooleanField(blank=True, help_text='Do you understand why the decision was made?', null=True, verbose_name='understands decision')),
                ('accepts_fairness', models.BooleanField(blank=True, help_text='Even if you disagree, do you believe the process was fair?', null=True, verbose_name='accepts fairness')),
                ('would_use_again', models.BooleanField(blank=True, help_text='Would you use this platform again?', null=True, verbose_name='would use again')),
                ('feedback', models.TextField(blank=True, help_text='Optional comments', verbose_name='feedback')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='sent at')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='responded at')),
                ('judgment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='disputes.judgment', verbose_name='judgment')),
            ],
            options={
                'verbose_name': 'post-judgment survey',
                'verbose_name_plural': 'post-judgment surveys',
                'db_table': 'disputes_post_judgment_survey',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('verdict_balance', 'Verdict Balance (Owner vs Renter)'), ('avg_resolution_time', 'Average Resolution Time'), ('consistency_trend', 'Consistency Trend'), ('appeal_rate', 'Appeal Rate'), ('settlement_rate', 'Pre-Dispute Settlement Rate')], db_index=True, max_length=50, verbose_name='metric type')),
                ('category', models.CharField(blank=True, help_text='Null = overall metric', max_length=100, null=True, verbose_name='category')),
                ('period_start', models.DateField(verbose_name='period start')),
                ('period_end', models.DateField(verbose_name='period end')),
                ('value_numeric', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='numeric value')),
                ('value_json', models.JSONField(blank=True, help_text='For multi-dimensional metrics', null=True, verbose_name='complex value')),
                ('computed_at', models.DateTimeField(auto_now=True, verbose_name='computed at')),
            ],
            options={
                'verbose_name': 'public metric',
                'verbose_name_plural': 'public metrics',
                'db_table': 'disputes_public_metrics',
                'ordering': ['-period_start'],
                'unique_together': {('metric_type', 'category', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='MetricContextCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_explanation', models.TextField(help_text='Why this number? What factors contributed?', verbose_name='context explanation')),
                ('counter_narrative', models.TextField(blank=True, help_text='What would change if conditions were different?', verbose_name='counter narrative')),
                ('sample_scenarios', models.JSONField(default=list, help_text='[{"condition": "With photo", "outcome": "78% owner"}]', verbose_name='sample scenarios')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='context_card', to='disputes.publicmetrics', verbose_name='metric')),
            ],
            options={
                'verbose_name': 'metric context card',
                'verbose_name_plural': 'metric context cards',
                'db_table': 'disputes_metric_context_card',
            },
        ),
        migrations.CreateModel(
            name='UserReputationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('frivolous_appeal', 'Frivolous Appeal (Rejected by Panel)'), ('emergency_abuse', 'Emergency Escalation Unjustified'), ('evidence_manipulation', 'Evidence Manipulation Detected'), ('repeated_filing', 'Repeated Filing of Similar Cases')], db_index=True, max_length=50, verbose_name='event type')),
                ('detection_method', models.CharField(help_text='panel_rejection, AI_flag, timestamp_anomaly, etc.', max_length=100, verbose_name='detection method')),
                ('severity', models.IntegerField(default=1, help_text='1-5, higher = more serious', verbose_name='severity')),
                ('logged_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='logged at')),
                ('action', models.CharField(choices=[('warning', 'Warning Issued'), ('priority_downgrade', 'Priority Downgraded'), ('scrutiny_increase', 'Scrutiny Level Increased'), ('escalation', 'Escalated to Human Review')], max_length=50, verbose_name='action taken')),
                ('notes', models.TextField(blank=True, verbose_name='internal notes')),
                ('related_dispute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reputation_events', to='disputes.dispute', verbose_name='related dispute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reputation_logs', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user reputation log',
                'verbose_name_plural': 'user reputation logs',
                'db_table': 'disputes_user_reputation_log',
                'ordering': ['-logged_at'],
                'indexes': [models.Index(fields=['user', 'event_type'], name='disputes_us_user_id_fa90c5_idx'), models.Index(fields=['logged_at'], name='disputes_us_logged__cdf41d_idx')],
            },
        ),
    ]
