# Generated by Django 6.0.1 on 2026-02-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0011_anonymizedjudgment_postjudgmentsurvey_publicmetrics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicmetrics',
            name='metric_type',
            field=models.CharField(choices=[('verdict_balance', 'Verdict Balance (Owner vs Renter)'), ('consistency_distribution', 'Consistency Distribution'), ('category_breakdown', 'Category Breakdown'), ('evidence_patterns', 'Evidence Patterns'), ('avg_resolution_time', 'Average Resolution Time'), ('consistency_trend', 'Consistency Trend'), ('appeal_rate', 'Appeal Rate'), ('settlement_rate', 'Pre-Dispute Settlement Rate')], db_index=True, max_length=50, verbose_name='metric type'),
        ),
    ]
