# Generated by Django 6.0.1 on 2026-02-06 19:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0012_alter_publicmetrics_metric_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreputationlog',
            name='context',
            field=models.TextField(blank=True, help_text='Human-readable context', verbose_name='context'),
        ),
        migrations.AddField(
            model_name='userreputationlog',
            name='event_data',
            field=models.JSONField(blank=True, help_text='Additional pattern-specific data', null=True, verbose_name='event data'),
        ),
        migrations.AddField(
            model_name='userreputationlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='timestamp'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userreputationlog',
            name='action',
            field=models.CharField(blank=True, choices=[('warning', 'Warning Issued'), ('priority_downgrade', 'Priority Downgraded'), ('scrutiny_increase', 'Scrutiny Level Increased'), ('escalation', 'Escalated to Human Review')], default='', max_length=50, verbose_name='action taken'),
        ),
        migrations.AlterField(
            model_name='userreputationlog',
            name='detection_method',
            field=models.CharField(blank=True, default='automatic', help_text='panel_rejection, AI_flag, timestamp_anomaly, etc.', max_length=100, verbose_name='detection method'),
        ),
        migrations.AlterField(
            model_name='userreputationlog',
            name='event_type',
            field=models.CharField(choices=[('frivolous_appeal', 'Frivolous Appeal (Rejected by Panel)'), ('emergency_abuse', 'Emergency Escalation Unjustified'), ('evidence_manipulation', 'Evidence Manipulation Detected'), ('repeated_filing', 'Repeated Filing of Similar Cases'), ('PATTERN_DETECTED', 'Abuse Pattern Detected'), ('WARNING_ISSUED', 'Warning Issued to User')], db_index=True, max_length=50, verbose_name='event type'),
        ),
    ]
