# Generated by Django 5.2.9 on 2026-02-07 18:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0010_verticalreadinessaudit"),
        ("disputes", "0013_userreputationlog_context_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="evidencelog",
            index=models.Index(
                fields=["booking", "-timestamp"], name="disputes_ev_booking_0d07bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="evidencelog",
            index=models.Index(
                fields=["dispute", "-timestamp"], name="disputes_ev_dispute_9b9386_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="evidencelog",
            index=models.Index(
                fields=["action", "-timestamp"], name="disputes_ev_action_34c5e2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="judgment",
            index=models.Index(
                fields=["dispute", "status"], name="disputes_ju_dispute_2c248e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="judgment",
            index=models.Index(
                fields=["dispute", "-created_at"], name="disputes_ju_dispute_588ac4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="judgment",
            index=models.Index(
                fields=["status", "-finalized_at"], name="disputes_ju_status_884655_idx"
            ),
        ),
    ]
