# Generated by Django 5.2.9 on 2026-02-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0014_add_judgment_evidence_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencelog',
            name='previous_hash',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Previous Log Hash'),
        ),
    ]
