# Generated by Django 5.2.9 on 2026-02-09 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0015_evidencelog_previous_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_round', models.IntegerField(default=1, verbose_name='Current Round')),
                ('max_rounds', models.IntegerField(default=3, verbose_name='Max Rounds')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('status', models.CharField(choices=[('active', 'Active'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], db_index=True, default='active', max_length=20)),
                ('dispute', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mediation_session', to='disputes.dispute', verbose_name='dispute')),
            ],
            options={
                'verbose_name': 'جلسة الوساطة',
                'verbose_name_plural': 'جلسات الوساطة',
            },
        ),
        migrations.CreateModel(
            name='SettlementOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('system', 'System AI'), ('owner', 'Owner'), ('tenant', 'Tenant')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Offer Amount')),
                ('reasoning', models.TextField(blank=True, verbose_name='Reasoning')),
                ('is_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cited_precedents', models.ManyToManyField(blank=True, related_name='settlement_citations', to='disputes.judgment', verbose_name='Cited Precedents')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='disputes.mediationsession', verbose_name='session')),
            ],
            options={
                'verbose_name': 'عرض التسوية',
                'verbose_name_plural': 'عروض التسوية',
                'ordering': ['-created_at'],
            },
        ),
    ]
