# Generated by Django 6.0.1 on 2026-02-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0016_mediationsession_settlementoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlementoffer',
            name='confidence_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum fair value (confidence interval)', max_digits=10, null=True, verbose_name='Confidence Maximum'),
        ),
        migrations.AddField(
            model_name='settlementoffer',
            name='confidence_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum fair value (confidence interval)', max_digits=10, null=True, verbose_name='Confidence Minimum'),
        ),
        migrations.AddField(
            model_name='settlementoffer',
            name='explainability_version',
            field=models.CharField(default='v1-plain-language', help_text='Tracks explanation format version (Phase 43)', max_length=20, verbose_name='Explainability Version'),
        ),
    ]
