# Generated by Django 6.0.1 on 2026-02-10 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0017_phase_43_explainability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='settlementoffer',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approved At'),
        ),
        migrations.AddField(
            model_name='settlementoffer',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_offers', to=settings.AUTH_USER_MODEL, verbose_name='Approved By'),
        ),
        migrations.AddField(
            model_name='settlementoffer',
            name='status',
            field=models.CharField(choices=[('pending_review', 'Pending Judicial Review'), ('visible', 'Visible to Parties'), ('rejected', 'Rejected by Admin')], default='visible', max_length=20, verbose_name='Visibility Status'),
        ),
    ]
