# Generated by Django 6.0.1 on 2026-02-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0018_phase_44_approval_workflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('value', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'system_flags',
            },
        ),
    ]
