# Generated by Django 6.0.1 on 2026-02-12 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0019_systemflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='judicial_panel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes', to='disputes.judicialpanel', verbose_name='Judicial Panel'),
        ),
    ]
