# Generated by Django 6.0.1 on 2026-02-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0020_dispute_judicial_panel'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='claimed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Claimed Amount'),
        ),
    ]
