# Generated by Django 6.0.3 on 2026-03-21 08:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0021_dispute_claimed_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgment',
            name='split_renter_percentage',
            field=models.IntegerField(blank=True, help_text='Percentage of escrow allocated to renter in a split verdict (1-99)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Split Renter Percentage'),
        ),
    ]
