# Generated by Django 5.1.2 on 2026-04-06 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_alter_booking_status_and_more'),
        ('disputes', '0022_judgment_split_renter_percentage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='anonymizedjudgment',
            name='disputes_an_categor_8a9acb_idx',
        ),
        migrations.RemoveIndex(
            model_name='anonymizedjudgment',
            name='disputes_an_consist_addea1_idx',
        ),
        migrations.RemoveIndex(
            model_name='anonymizedjudgment',
            name='disputes_an_judgmen_887108_idx',
        ),
        migrations.RemoveIndex(
            model_name='anonymizedjudgment',
            name='disputes_an_uniquen_394f24_idx',
        ),
        migrations.RemoveIndex(
            model_name='userreputationlog',
            name='disputes_us_user_id_fa90c5_idx',
        ),
        migrations.RemoveIndex(
            model_name='userreputationlog',
            name='disputes_us_logged__cdf41d_idx',
        ),
        migrations.AddField(
            model_name='evidencelog',
            name='dispute_sequence',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='anonymizedjudgment',
            name='awarded_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='awarded ratio %'),
        ),
        migrations.AlterField(
            model_name='anonymizedjudgment',
            name='consistency_score',
            field=models.IntegerField(default=0, verbose_name='consistency score'),
        ),
        migrations.AlterField(
            model_name='anonymizedjudgment',
            name='evidence_types',
            field=models.JSONField(default=list, verbose_name='evidence types'),
        ),
        migrations.AlterField(
            model_name='anonymizedjudgment',
            name='geographic_region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='geographic region'),
        ),
        migrations.AlterField(
            model_name='anonymizedjudgment',
            name='judgment_date',
            field=models.DateField(db_index=True, verbose_name='judgment date'),
        ),
        migrations.AlterField(
            model_name='anonymizedjudgment',
            name='judgment_hash',
            field=models.CharField(max_length=64, unique=True, verbose_name='judgment hash'),
        ),
        migrations.AlterField(
            model_name='anonymizedjudgment',
            name='publication_delayed_until',
            field=models.DateField(blank=True, null=True, verbose_name='publication delayed until'),
        ),
        migrations.AlterField(
            model_name='anonymizedjudgment',
            name='ruling_summary',
            field=models.TextField(verbose_name='ruling summary'),
        ),
        migrations.AlterField(
            model_name='anonymizedjudgment',
            name='uniqueness_score',
            field=models.IntegerField(default=0, verbose_name='uniqueness score'),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='status',
            field=models.CharField(choices=[('open', 'Open (Legacy Alias)'), ('filed', 'Filed (Pending Admissibility)'), ('admissible', 'Admissible (Discovery Open)'), ('inadmissible', 'Inadmissible (Rejected)'), ('under_review', 'Under Review (Deliberation)'), ('judgment_provisional', 'Judgment Provisional'), ('judgment_final', 'Judgment Final'), ('resolved', 'Resolved (Legacy Alias)'), ('closed', 'Closed')], default='filed', max_length=50, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='judgment',
            name='judge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='judgments_authored', to=settings.AUTH_USER_MODEL, verbose_name='judge'),
        ),
        migrations.AlterField(
            model_name='judgment',
            name='verdict',
            field=models.CharField(choices=[('favor_tenant', 'Favor Tenant'), ('favor_renter', 'Favor Renter (Legacy Alias)'), ('favor_owner', 'Favor Owner'), ('split', 'Split Decision'), ('partial', 'Partial Decision (Legacy Alias)'), ('dismissed', 'Dismissed')], max_length=20, verbose_name='verdict'),
        ),
        migrations.AlterField(
            model_name='metriccontextcard',
            name='context_explanation',
            field=models.TextField(verbose_name='context explanation'),
        ),
        migrations.AlterField(
            model_name='metriccontextcard',
            name='counter_narrative',
            field=models.TextField(blank=True, verbose_name='counter narrative'),
        ),
        migrations.AlterField(
            model_name='metriccontextcard',
            name='sample_scenarios',
            field=models.JSONField(default=list, verbose_name='sample scenarios'),
        ),
        migrations.AlterField(
            model_name='postjudgmentsurvey',
            name='accepts_fairness',
            field=models.BooleanField(blank=True, null=True, verbose_name='accepts fairness'),
        ),
        migrations.AlterField(
            model_name='postjudgmentsurvey',
            name='feedback',
            field=models.TextField(blank=True, verbose_name='feedback'),
        ),
        migrations.AlterField(
            model_name='postjudgmentsurvey',
            name='understands_decision',
            field=models.BooleanField(blank=True, null=True, verbose_name='understands decision'),
        ),
        migrations.AlterField(
            model_name='postjudgmentsurvey',
            name='would_use_again',
            field=models.BooleanField(blank=True, null=True, verbose_name='would use again'),
        ),
        migrations.AlterField(
            model_name='publicmetrics',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='publicmetrics',
            name='value_json',
            field=models.JSONField(blank=True, null=True, verbose_name='complex value'),
        ),
        migrations.AlterField(
            model_name='settlementoffer',
            name='confidence_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Confidence Maximum'),
        ),
        migrations.AlterField(
            model_name='settlementoffer',
            name='confidence_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Confidence Minimum'),
        ),
        migrations.AlterField(
            model_name='settlementoffer',
            name='explainability_version',
            field=models.CharField(default='v1-plain-language', max_length=20, verbose_name='Explainability Version'),
        ),
        migrations.AlterField(
            model_name='userreputationlog',
            name='context',
            field=models.TextField(blank=True, verbose_name='context'),
        ),
        migrations.AlterField(
            model_name='userreputationlog',
            name='detection_method',
            field=models.CharField(blank=True, default='automatic', max_length=100, verbose_name='detection method'),
        ),
        migrations.AlterField(
            model_name='userreputationlog',
            name='event_data',
            field=models.JSONField(blank=True, null=True, verbose_name='event data'),
        ),
        migrations.AlterField(
            model_name='userreputationlog',
            name='severity',
            field=models.IntegerField(default=1, verbose_name='severity'),
        ),
        migrations.AddIndex(
            model_name='evidencelog',
            index=models.Index(fields=['dispute', 'dispute_sequence'], name='disputes_ev_dispute_00f96b_idx'),
        ),
    ]
