# Generated by Django 6.0.1 on 2026-02-02 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('title_ar', models.CharField(max_length=200, verbose_name='title (Arabic)')),
                ('banner_type', models.CharField(choices=[('hero', 'Hero Banner'), ('promotion', 'Promotion'), ('announcement', 'Announcement'), ('sidebar', 'Sidebar')], default='promotion', max_length=20, verbose_name='banner type')),
                ('position', models.CharField(choices=[('home_top', 'Home Top'), ('home_middle', 'Home Middle'), ('home_bottom', 'Home Bottom'), ('products_top', 'Products Top'), ('sidebar', 'Sidebar')], default='home_top', max_length=20, verbose_name='position')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='image')),
                ('link_url', models.URLField(blank=True, null=True, verbose_name='link URL')),
                ('link_text', models.CharField(blank=True, max_length=100, verbose_name='link text')),
                ('link_text_ar', models.CharField(blank=True, max_length=100, verbose_name='link text (Arabic)')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('description_ar', models.TextField(blank=True, verbose_name='description (Arabic)')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='start date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='end date')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('click_count', models.IntegerField(default=0, verbose_name='click count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'البانر',
                'verbose_name_plural': 'البانرات',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['position', 'is_active'], name='cms_banner_positio_459444_idx'), models.Index(fields=['banner_type', 'is_active'], name='cms_banner_banner__f0f6bb_idx')],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='question')),
                ('question_ar', models.CharField(max_length=500, verbose_name='question (Arabic)')),
                ('answer', models.TextField(verbose_name='answer')),
                ('answer_ar', models.TextField(verbose_name='answer (Arabic)')),
                ('category', models.CharField(choices=[('general', 'General'), ('booking', 'Booking'), ('payment', 'Payment'), ('delivery', 'Delivery'), ('returns', 'Returns'), ('account', 'Account'), ('other', 'Other')], default='general', max_length=20, verbose_name='category')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('view_count', models.IntegerField(default=0, verbose_name='view count')),
                ('helpful_count', models.IntegerField(default=0, verbose_name='helpful count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'السؤال الشائع',
                'verbose_name_plural': 'الأسئلة الشائعة',
                'ordering': ['order', 'category', 'question'],
                'indexes': [models.Index(fields=['category', 'is_featured'], name='cms_faq_categor_a38798_idx')],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('title_ar', models.CharField(max_length=200, verbose_name='title (Arabic)')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('excerpt', models.TextField(blank=True, max_length=500, verbose_name='excerpt')),
                ('excerpt_ar', models.TextField(blank=True, max_length=500, verbose_name='excerpt (Arabic)')),
                ('content', models.TextField(verbose_name='content')),
                ('content_ar', models.TextField(verbose_name='content (Arabic)')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='featured image')),
                ('meta_description', models.CharField(blank=True, max_length=255, verbose_name='meta description')),
                ('meta_description_ar', models.CharField(blank=True, max_length=255, verbose_name='meta description (Arabic)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='status')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured')),
                ('view_count', models.IntegerField(default=0, verbose_name='view count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name': 'مقال المدونة',
                'verbose_name_plural': 'مقالات المدونة',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['slug', 'status'], name='cms_blogpos_slug_090db4_idx'), models.Index(fields=['status', 'published_at'], name='cms_blogpos_status_c3c767_idx')],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('title_ar', models.CharField(max_length=200, verbose_name='title (Arabic)')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('page_type', models.CharField(choices=[('about', 'About Us'), ('terms', 'Terms of Service'), ('privacy', 'Privacy Policy'), ('contact', 'Contact'), ('faq', 'FAQ'), ('custom', 'Custom Page')], default='custom', max_length=20, verbose_name='page type')),
                ('content', models.TextField(blank=True, verbose_name='content')),
                ('content_ar', models.TextField(blank=True, verbose_name='content (Arabic)')),
                ('meta_description', models.CharField(blank=True, max_length=255, verbose_name='meta description')),
                ('meta_description_ar', models.CharField(blank=True, max_length=255, verbose_name='meta description (Arabic)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='status')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured')),
                ('order', models.IntegerField(default=0, help_text='Display order', verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages_created', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated_by')),
            ],
            options={
                'verbose_name': 'الصفحة',
                'verbose_name_plural': 'الصفحات',
                'ordering': ['order', 'title'],
                'indexes': [models.Index(fields=['slug', 'status'], name='cms_page_slug_28f1ee_idx'), models.Index(fields=['page_type', 'status'], name='cms_page_page_ty_165c09_idx')],
            },
        ),
    ]
