# Generated by Django 5.2.9 on 2026-02-13 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('action', models.CharField(choices=[('CREATE', 'Creation'), ('UPDATE', 'Update'), ('DELETE', 'Deletion'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('RISK_FLAG', 'Risk Flag'), ('DISPUTE_ACTION', 'Dispute Action'), ('ESCROW_MOVE', 'Escrow Movement'), ('SECURITY_ALERT', 'Security Alert')], max_length=50)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='JSON diff of changes')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Context (User Agent, etc.)')),
                ('object_id', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action', 'timestamp'], name='audit_audit_action_2a1328_idx'), models.Index(fields=['actor', 'timestamp'], name='audit_audit_actor_i_6355cc_idx')],
            },
        ),
    ]
