# Generated by Django 5.2.9 on 2026-01-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenancePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='start datetime')),
                ('end_datetime', models.DateTimeField(verbose_name='end datetime')),
                ('blocks_bookings', models.BooleanField(default=True, verbose_name='blocks bookings')),
            ],
            options={
                'verbose_name': 'Maintenance Period',
                'verbose_name_plural': 'Maintenance Periods',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('cleaning', 'Cleaning'), ('repair', 'Repair'), ('inspection', 'Inspection'), ('deep_clean', 'Deep Cleaning')], max_length=20, verbose_name='maintenance type')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20, verbose_name='status')),
                ('scheduled_start', models.DateTimeField(verbose_name='scheduled start')),
                ('scheduled_end', models.DateTimeField(verbose_name='scheduled end')),
                ('actual_start', models.DateTimeField(blank=True, null=True, verbose_name='actual start')),
                ('actual_end', models.DateTimeField(blank=True, null=True, verbose_name='actual end')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('cost', models.DecimalField(decimal_places=2, default=0, help_text='Maintenance cost if any', max_digits=10, verbose_name='cost')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Maintenance Record',
                'verbose_name_plural': 'Maintenance Records',
                'ordering': ['-scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('cleaning', 'Cleaning'), ('repair', 'Repair'), ('inspection', 'Inspection'), ('deep_clean', 'Deep Cleaning')], default='cleaning', max_length=20, verbose_name='maintenance type')),
                ('duration_hours', models.IntegerField(default=2, help_text='Duration in hours needed for maintenance', verbose_name='duration (hours)')),
                ('required_between_rentals', models.BooleanField(default=True, help_text='Whether this maintenance is required between each rental', verbose_name='required between rentals')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Maintenance Schedule',
                'verbose_name_plural': 'Maintenance Schedules',
                'ordering': ['product', 'maintenance_type'],
            },
        ),
    ]
