# Generated by Django 5.2.9 on 2026-01-02 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
        ('maintenance', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerecord',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='products.product'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='related_booking',
            field=models.ForeignKey(blank=True, help_text='Booking that triggered this maintenance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_records', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='maintenanceperiod',
            name='maintenance_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='period', to='maintenance.maintenancerecord'),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='products.product'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['product', 'status'], name='maintenance_product_765039_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['scheduled_start', 'scheduled_end'], name='maintenance_schedul_0930d2_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceperiod',
            index=models.Index(fields=['start_datetime', 'end_datetime'], name='maintenance_start_d_e7610d_idx'),
        ),
    ]
