# Generated by Django 6.0.1 on 2026-02-02 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_options_alter_cart_options_and_more'),
        ('maintenance', '0002_initial'),
        ('products', '0003_productvariant_wishlist_alter_category_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenanceperiod',
            options={'verbose_name': 'فترة الصيانة', 'verbose_name_plural': 'فترات الصيانة'},
        ),
        migrations.AlterModelOptions(
            name='maintenancerecord',
            options={'ordering': ['-scheduled_start'], 'verbose_name': 'سجل الصيانة', 'verbose_name_plural': 'سجلات الصيانة'},
        ),
        migrations.AlterModelOptions(
            name='maintenanceschedule',
            options={'ordering': ['product', 'maintenance_type'], 'verbose_name': 'جدول الصيانة', 'verbose_name_plural': 'جداول الصيانة'},
        ),
        migrations.AlterField(
            model_name='maintenanceperiod',
            name='maintenance_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='period', to='maintenance.maintenancerecord', verbose_name='maintenance_record'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenances', to=settings.AUTH_USER_MODEL, verbose_name='assigned_to'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='products.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='related_booking',
            field=models.ForeignKey(blank=True, help_text='Booking that triggered this maintenance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_records', to='bookings.booking', verbose_name='related_booking'),
        ),
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='products.product', verbose_name='product'),
        ),
    ]
