// =============================================================================
// STANDARD Rent - Mock Data (Algerian Luxury Clothing Rental)
// كراء ملابس فاخرة في الجزائر
// =============================================================================

// ---- Categories ----
export const categories = [
  { id: 1, name_ar: "فساتين زفاف", slug: "wedding-dresses", product_count: 5, icon: "https://picsum.photos/seed/cat-wedding/100/100" },
  { id: 2, name_ar: "بدلات رجالية", slug: "mens-suits", product_count: 3, icon: "https://picsum.photos/seed/cat-suits/100/100" },
  { id: 3, name_ar: "قفطان جزائري", slug: "caftan-algerian", product_count: 4, icon: "https://picsum.photos/seed/cat-caftan/100/100" },
  { id: 4, name_ar: "قرطاسيات", slug: "karstassiya", product_count: 3, icon: "https://picsum.photos/seed/cat-karstass/100/100" },
  { id: 5, name_ar: "جلابيات فاخرة", slug: "galabiya-luxury", product_count: 3, icon: "https://picsum.photos/seed/cat-galabiya/100/100" },
  { id: 6, name_ar: "أزياء مناسبات", slug: "occasion-wear", product_count: 2, icon: "https://picsum.photos/seed/cat-occasion/100/100" },
];

// ---- Products (20 items) ----
export const products = [
  {
    id: 1,
    name: "Wedding Dress Princess Al Zahra",
    name_ar: "فستان زفاف أميرة الزهراء",
    slug: "fatan-zifaf-amira-al-zahra",
    description: "فستان زفاف فاخر بتصميم أميري مطرّز يدوياً بأطراف ذهبية، مثالي لحفلات الزفاف الكبرى في الجزائر",
    price_per_day: 25000,
    images: [
      { id: 1, url: "https://picsum.photos/seed/product1a/600/800", is_main: true },
      { id: 2, url: "https://picsum.photos/seed/product1b/600/800", is_main: false },
      { id: 3, url: "https://picsum.photos/seed/product1c/600/800", is_main: false },
    ],
    primary_image: "https://picsum.photos/seed/product1a/600/800",
    category: { id: 1, name_ar: "فساتين زفاف", slug: "wedding-dresses" },
    category_name: "فساتين زفاف",
    location: "قسنطينة",
    location_name: "قسنطينة",
    is_available: true,
    rating: 4.9,
    trust_score: 96,
    is_premium: true,
    is_verified: true,
    owner_id: 1,
    size_options: ["S", "M", "L", "XL"],
    color_options: ["أبيض", "عاجي"],
  },
  {
    id: 2,
    name: "Classic Black Tuxedo",
    name_ar: "بدلة سوداء كلاسيكية",
    slug: "badla-sawda-classic",
    description: "بدلة رسمية سوداء بتصميم كلاسيكي أنيق، مناسبة للأعراس والمناسبات الرسمية",
    price_per_day: 8000,
    images: [
      { id: 4, url: "https://picsum.photos/seed/product2a/600/800", is_main: true },
      { id: 5, url: "https://picsum.photos/seed/product2b/600/800", is_main: false },
    ],
    primary_image: "https://picsum.photos/seed/product2a/600/800",
    category: { id: 2, name_ar: "بدلات رجالية", slug: "mens-suits" },
    category_name: "بدلات رجالية",
    location: "الجزائر العاصمة",
    location_name: "الجزائر العاصمة",
    is_available: true,
    rating: 4.7,
    trust_score: 92,
    is_premium: false,
    is_verified: true,
    owner_id: 2,
    size_options: ["M", "L", "XL", "XXL"],
    color_options: ["أسود", "كحلي غامق"],
  },
  {
    id: 3,
    name: "Royal Algerian Caftan Gold",
    name_ar: "قفطان جزائري ملكي ذهبي",
    slug: "qaftan-malaki-dhahabi",
    description: "قفطان جزائري فاخر مطرّز بخيوط الذهب الخالص، إرث من الحرفية الجزائرية العريقة",
    price_per_day: 18000,
    images: [
      { id: 6, url: "https://picsum.photos/seed/product3a/600/800", is_main: true },
      { id: 7, url: "https://picsum.photos/seed/product3b/600/800", is_main: false },
      { id: 8, url: "https://picsum.photos/seed/product3c/600/800", is_main: false },
    ],
    primary_image: "https://picsum.photos/seed/product3a/600/800",
    category: { id: 3, name_ar: "قفطان جزائري", slug: "caftan-algerian" },
    category_name: "قفطان جزائري",
    location: "تلمسان",
    location_name: "تلمسان",
    is_available: true,
    rating: 5.0,
    trust_score: 98,
    is_premium: true,
    is_verified: true,
    owner_id: 3,
    size_options: ["M", "L", "XL"],
    color_options: ["ذهبي", "أحمر ذهبي"],
  },
  {
    id: 4,
    name: "Elegant Karstassiya Blouse",
    name_ar: "قرطاسية أنيقة",
    slug: "kartasiya-aniqa",
    description: "قرطاسية جزائرية تقليدية بتطريز يدوي دقيق، مثالية للمناسبات الخاصة والأعراس",
    price_per_day: 10000,
    images: [
      { id: 9, url: "https://picsum.photos/seed/product4a/600/800", is_main: true },
      { id: 10, url: "https://picsum.photos/seed/product4b/600/800", is_main: false },
    ],
    primary_image: "https://picsum.photos/seed/product4a/600/800",
    category: { id: 4, name_ar: "قرطاسيات", slug: "karstassiya" },
    category_name: "قرطاسيات",
    location: "وهران",
    location_name: "وهران",
    is_available: true,
    rating: 4.8,
    trust_score: 90,
    is_premium: true,
    is_verified: true,
    owner_id: 4,
    size_options: ["S", "M", "L"],
    color_options: ["أزرق سماوي", "وردي"],
  },
  {
    id: 5,
    name: "Luxury Galabiya Embroidered",
    name_ar: "جلابية فاخرة مطرّزة",
    slug: "galabiya-fakhira-mutarriza",
    description: "جلابية فاخرة مطرّزة بخيوط الحرير والذهب، تجمع بين الأصالة والأناقة العصرية",
    price_per_day: 12000,
    images: [
      { id: 11, url: "https://picsum.photos/seed/product5a/600/800", is_main: true },
      { id: 12, url: "https://picsum.photos/seed/product5b/600/800", is_main: false },
    ],
    primary_image: "https://picsum.photos/seed/product5a/600/800",
    category: { id: 5, name_ar: "جلابيات فاخرة", slug: "galabiya-luxury" },
    category_name: "جلابيات فاخرة",
    location: "عنابة",
    location_name: "عنابة",
    is_available: true,
    rating: 4.6,
    trust_score: 85,
    is_premium: false,
    is_verified: true,
    owner_id: 5,
    size_options: ["M", "L", "XL", "XXL"],
    color_options: ["أبيض", "بيج"],
  },
  {
    id: 6,
    name: "Bridal Caftan Sapphire",
    name_ar: "قفطان عروس أزرق ياقوتي",
    slug: "qaftan-arous-azraq",
    description: "قفطان عروس بلون أزرق ياقوتي نادر مع تطريز يدوي فاخر، قطعة فريدة من نوعها",
    price_per_day: 22000,
    images: [
      { id: 13, url: "https://picsum.photos/seed/product6a/600/800", is_main: true },
      { id: 14, url: "https://picsum.photos/seed/product6b/600/800", is_main: false },
      { id: 15, url: "https://picsum.photos/seed/product6c/600/800", is_main: false },
    ],
    primary_image: "https://picsum.photos/seed/product6a/600/800",
    category: { id: 3, name_ar: "قفطان جزائري", slug: "caftan-algerian" },
    category_name: "قفطان جزائري",
    location: "قسنطينة",
    location_name: "قسنطينة",
    is_available: true,
    rating: 4.9,
    trust_score: 95,
    is_premium: true,
    is_verified: true,
    owner_id: 1,
    size_options: ["S", "M", "L"],
    color_options: ["أزرق ياقوتي"],
  },
  {
    id: 7,
    name: "Evening Gown Rose",
    name_ar: "فستان سهرة وردي",
    slug: "fatan-sahra-waradi",
    description: "فستان سهرة أنيق باللون الوردي مع تفاصيل كريستالية، مثالي للحفلات والسهرات الراقية",
    price_per_day: 9000,
    images: [
      { id: 16, url: "https://picsum.photos/seed/product7a/600/800", is_main: true },
      { id: 17, url: "https://picsum.photos/seed/product7b/600/800", is_main: false },
    ],
    primary_image: "https://picsum.photos/seed/product7a/600/800",
    category: { id: 6, name_ar: "أزياء مناسبات", slug: "occasion-wear" },
    category_name: "أزياء مناسبات",
    location: "البليدة",
    location_name: "البليدة",
    is_available: true,
    rating: 4.5,
    trust_score: 82,
    is_premium: false,
    is_verified: false,
    owner_id: 6,
    size_options: ["S", "M", "L"],
    color_options: ["وردي", "خوخي"],
  },
  {
    id: 8,
    name: "Men's Wedding Suit Ivory",
    name_ar: "بدلة زفاف رجالية عاجية",
    slug: "badla-zifaf-rija-iwajiya",
    description: "بدلة زفاف رجالية باللون العاجي مع ربطة عنق حريرية مناسبة لحفلات الزفاف الراقية",
    price_per_day: 12000,
    images: [
      { id: 18, url: "https://picsum.photos/seed/product8a/600/800", is_main: true },
      { id: 19, url: "https://picsum.photos/seed/product8b/600/800", is_main: false },
    ],
    primary_image: "https://picsum.photos/seed/product8a/600/800",
    category: { id: 2, name_ar: "بدلات رجالية", slug: "mens-suits" },
    category_name: "بدلات رجالية",
    location: "الجزائر العاصمة",
    location_name: "الجزائر العاصمة",
    is_available: true,
    rating: 4.8,
    trust_score: 91,
    is_premium: true,
    is_verified: true,
    owner_id: 2,
    size_options: ["M", "L", "XL"],
    color_options: ["عاجي", "رمادي فاتح"],
  },
  {
    id: 9,
    name: "Traditional Caftan Red",
    name_ar: "قفطان تقليدي أحمر",
    slug: "qaftan-taqlidi-ahmar",
    description: "قفطان جزائري تقليدي باللون الأحمر مع تطريز عربي أصيل، مناسب لجميع المناسبات",
    price_per_day: 15000,
    images: [
      { id: 20, url: "https://picsum.photos/seed/product9a/600/800", is_main: true },
      { id: 21, url: "https://picsum.photos/seed/product9b/600/800", is_main: false },
    ],
    primary_image: "https://picsum.photos/seed/product9a/600/800",
    category: { id: 3, name_ar: "قفطان جزائري", slug: "caftan-algerian" },
    category_name: "قفطان جزائري",
    location: "سطيف",
    location_name: "سطيف",
    is_available: true,
    rating: 4.7,
    trust_score: 88,
    is_premium: false,
    is_verified: true,
    owner_id: 7,
    size_options: ["S", "M", "L", "XL"],
    color_options: ["أحمر", "أحمر غامق"],
  },
  {
    id: 10,
    name: "Galabiya Royal White",
    name_ar: "جلابية ملكية بيضاء",
    slug: "galabiya-malakiya-bayda",
    description: "جلابية بيضاء ملكية مع تطريز ذهبي دقيق، مثالية لحفلات الخطوبة والمناسبات الخاصة",
    price_per_day: 11000,
    images: [
      { id: 22, url: "https://picsum.photos/seed/product10a/600/800", is_main: true },
      { id: 23, url: "https://picsum.photos/seed/product10b/600/800", is_main: false },
    ],
    primary_image: "https://picsum.photos/seed/product10a/600/800",
    category: { id: 5, name_ar: "جلابيات فاخرة", slug: "galabiya-luxury" },
    category_name: "جلابيات فاخرة",
    location: "تلمسان",
    location_name: "تلمسان",
    is_available: true,
    rating: 4.4,
    trust_score: 80,
    is_premium: false,
    is_verified: true,
    owner_id: 3,
    size_options: ["M", "L", "XL"],
    color_options: ["أبيض", "أبيض مائل للكريمي"],
  },
  {
    id: 11,
    name: "Diamond Wedding Dress",
    name_ar: "فستان زفاف مرصّع بالألماس",
    slug: "fatan-zifaf-mursa-almaz",
    description: "فستان زفاف استثنائي مرصّع بحجارة الألماس المقلّدة، يمنحك إطلالة ملكية لا تُنسى",
    price_per_day: 25000,
    images: [
      { id: 24, url: "https://picsum.photos/seed/product11a/600/800", is_main: true },
      { id: 25, url: "https://picsum.photos/seed/product11b/600/800", is_main: false },
      { id: 26, url: "https://picsum.photos/seed/product11c/600/800", is_main: false },
    ],
    primary_image: "https://picsum.photos/seed/product11a/600/800",
    category: { id: 1, name_ar: "فساتين زفاف", slug: "wedding-dresses" },
    category_name: "فساتين زفاف",
    location: "الجزائر العاصمة",
    location_name: "الجزائر العاصمة",
    is_available: false,
    rating: 5.0,
    trust_score: 97,
    is_premium: true,
    is_verified: true,
    owner_id: 8,
    size_options: ["S", "M"],
    color_options: ["أبيض ثلجي"],
  },
  {
    id: 12,
    name: "Karstassiya Gold Thread",
    name_ar: "قرطاسية بخيوط الذهب",
    slug: "kartasiya-khiut-dhahab",
    description: "قرطاسية فاخرة مطرّزة بخيوط الذهب على قماش الحرير، تحفة فنية جزائرية أصيلة",
    price_per_day: 14000,
    images: [
      { id: 27, url: "https://picsum.photos/seed/product12a/600/800", is_main: true },
      { id: 28, url: "https://picsum.photos/seed/product12b/600/800", is_main: false },
    ],
    primary_image: "https://picsum.photos/seed/product12a/600/800",
    category: { id: 4, name_ar: "قرطاسيات", slug: "karstassiya" },
    category_name: "قرطاسيات",
    location: "قسنطينة",
    location_name: "قسنطينة",
    is_available: true,
    rating: 4.8,
    trust_score: 93,
    is_premium: true,
    is_verified: true,
    owner_id: 1,
    size_options: ["S", "M", "L"],
    color_options: ["ذهبي", "أسود وذهبي"],
  },
  {
    id: 13,
    name: "Modern Caftan Turquoise",
    name_ar: "قفطان عصري تركوازي",
    slug: "qaftan-asari-turkuazi",
    description: "قفطان بتصميم عصري يمزج بين التراث الجزائري والموضة الحديثة بلون تركوازي ساحر",
    price_per_day: 13000,
    images: [
      { id: 29, url: "https://picsum.photos/seed/product13a/600/800", is_main: true },
      { id: 30, url: "https://picsum.photos/seed/product13b/600/800", is_main: false },
    ],
    primary_image: "https://picsum.photos/seed/product13a/600/800",
    category: { id: 3, name_ar: "قفطان جزائري", slug: "caftan-algerian" },
    category_name: "قفطان جزائري",
    location: "وهران",
    location_name: "وهران",
    is_available: true,
    rating: 4.6,
    trust_score: 86,
    is_premium: false,
    is_verified: true,
    owner_id: 4,
    size_options: ["S", "M", "L", "XL"],
    color_options: ["تركوازي", "فيروزي"],
  },
  {
    id: 14,
    name: "Wedding Dress Lace",
    name_ar: "فستان زفاف بدانتيل فرنسي",
    slug: "fatan-zifaf-dantil",
    description: "فستان زفاف بدانتيل فرنسي فاخر مع ذيل طويل، يجمع بين الرقيّ الغربي والأناقة الجزائرية",
    price_per_day: 20000,
    images: [
      { id: 31, url: "https://picsum.photos/seed/product14a/600/800", is_main: true },
      { id: 32, url: "https://picsum.photos/seed/product14b/600/800", is_main: false },
      { id: 33, url: "https://picsum.photos/seed/product14c/600/800", is_main: false },
    ],
    primary_image: "https://picsum.photos/seed/product14a/600/800",
    category: { id: 1, name_ar: "فساتين زفاف", slug: "wedding-dresses" },
    category_name: "فساتين زفاف",
    location: "البليدة",
    location_name: "البليدة",
    is_available: true,
    rating: 4.8,
    trust_score: 91,
    is_premium: true,
    is_verified: true,
    owner_id: 6,
    size_options: ["S", "M", "L"],
    color_options: ["أبيض", "عاجي"],
  },
  {
    id: 15,
    name: "Formal Navy Suit",
    name_ar: "بدلة رسمية كحلية",
    slug: "badla-rasmia-kuhliya",
    description: "بدلة رسمية باللون الكحلي مع قميص أبيض وربطة عنق سوداء، مثالية للمناسبات الرسمية",
    price_per_day: 7000,
    images: [
      { id: 34, url: "https://picsum.photos/seed/product15a/600/800", is_main: true },
      { id: 35, url: "https://picsum.photos/seed/product15b/600/800", is_main: false },
    ],
    primary_image: "https://picsum.photos/seed/product15a/600/800",
    category: { id: 2, name_ar: "بدلات رجالية", slug: "mens-suits" },
    category_name: "بدلات رجالية",
    location: "سطيف",
    location_name: "سطيف",
    is_available: true,
    rating: 4.3,
    trust_score: 78,
    is_premium: false,
    is_verified: false,
    owner_id: 7,
    size_options: ["M", "L", "XL", "XXL"],
    color_options: ["كحلي", "أسود"],
  },
  {
    id: 16,
    name: "Occasion Dress Emerald",
    name_ar: "فستان مناسبات زمردي",
    slug: "fatan-manasibat-zumrudi",
    description: "فستان أنيق بلون زمردي ساحر مع تطريز يدوي، مناسب لحفلات التخرج والمناسبات الخاصة",
    price_per_day: 8000,
    images: [
      { id: 36, url: "https://picsum.photos/seed/product16a/600/800", is_main: true },
      { id: 37, url: "https://picsum.photos/seed/product16b/600/800", is_main: false },
    ],
    primary_image: "https://picsum.photos/seed/product16a/600/800",
    category: { id: 6, name_ar: "أزياء مناسبات", slug: "occasion-wear" },
    category_name: "أزياء مناسبات",
    location: "عنابة",
    location_name: "عنابة",
    is_available: true,
    rating: 4.5,
    trust_score: 83,
    is_premium: false,
    is_verified: true,
    owner_id: 5,
    size_options: ["S", "M", "L"],
    color_options: ["زمردي", "أخضر داكن"],
  },
  {
    id: 17,
    name: "Galabiya Beige Embroidered",
    name_ar: "جلابية بيج مطرّزة",
    slug: "galabiya-bej-mutarriza",
    description: "جلابية بلون البيج مع تطريز تقليدي جزائري، أنيقة ومريحة في نفس الوقت",
    price_per_day: 6000,
    images: [
      { id: 38, url: "https://picsum.photos/seed/product17a/600/800", is_main: true },
      { id: 39, url: "https://picsum.photos/seed/product17b/600/800", is_main: false },
    ],
    primary_image: "https://picsum.photos/seed/product17a/600/800",
    category: { id: 5, name_ar: "جلابيات فاخرة", slug: "galabiya-luxury" },
    category_name: "جلابيات فاخرة",
    location: "الجزائر العاصمة",
    location_name: "الجزائر العاصمة",
    is_available: true,
    rating: 4.2,
    trust_score: 76,
    is_premium: false,
    is_verified: false,
    owner_id: 8,
    size_options: ["M", "L", "XL"],
    color_options: ["بيج", "عنابي"],
  },
  {
    id: 18,
    name: "Karstassiya Bridal Set",
    name_ar: "طقم قرطاسية عروس",
    slug: "taqm-kartasiya-arous",
    description: "طقم قرطاسية كامل للعروس يشمل البلوزة والسروال مع تطريز استثنائي بخيوط الذهب والفضة",
    price_per_day: 16000,
    images: [
      { id: 40, url: "https://picsum.photos/seed/product18a/600/800", is_main: true },
      { id: 41, url: "https://picsum.photos/seed/product18b/600/800", is_main: false },
      { id: 42, url: "https://picsum.photos/seed/product18c/600/800", is_main: false },
    ],
    primary_image: "https://picsum.photos/seed/product18a/600/800",
    category: { id: 4, name_ar: "قرطاسيات", slug: "karstassiya" },
    category_name: "قرطاسيات",
    location: "تلمسان",
    location_name: "تلمسان",
    is_available: true,
    rating: 4.9,
    trust_score: 94,
    is_premium: true,
    is_verified: true,
    owner_id: 3,
    size_options: ["S", "M", "L"],
    color_options: ["ذهبي", "أحمر وذهبي"],
  },
  {
    id: 19,
    name: "Wedding Dress Mermaid Style",
    name_ar: "فستان زفاف بستيلة الحوت",
    slug: "fatan-zifaf-hout",
    description: "فستان زفاف بتصميم ستيلة الحوت الأنيق مع تطريز كريستالي، مثالي للعروسات الراقيات",
    price_per_day: 23000,
    images: [
      { id: 43, url: "https://picsum.photos/seed/product19a/600/800", is_main: true },
      { id: 44, url: "https://picsum.photos/seed/product19b/600/800", is_main: false },
    ],
    primary_image: "https://picsum.photos/seed/product19a/600/800",
    category: { id: 1, name_ar: "فساتين زفاف", slug: "wedding-dresses" },
    category_name: "فساتين زفاف",
    location: "وهران",
    location_name: "وهران",
    is_available: true,
    rating: 4.7,
    trust_score: 89,
    is_premium: true,
    is_verified: true,
    owner_id: 4,
    size_options: ["S", "M"],
    color_options: ["أبيض", "عاجي فاتح"],
  },
  {
    id: 20,
    name: "Slim Fit Gray Suit",
    name_ar: "بدلة رمادية قصيرة",
    slug: "badla-ramadiya-qasira",
    description: "بدلة رمادية بقصة ضيقة أنيقة مع وسادة صدر حريرية، مناسبة للحفلات والسهرات الرسمية",
    price_per_day: 5000,
    images: [
      { id: 45, url: "https://picsum.photos/seed/product20a/600/800", is_main: true },
      { id: 46, url: "https://picsum.photos/seed/product20b/600/800", is_main: false },
    ],
    primary_image: "https://picsum.photos/seed/product20a/600/800",
    category: { id: 2, name_ar: "بدلات رجالية", slug: "mens-suits" },
    category_name: "بدلات رجالية",
    location: "قسنطينة",
    location_name: "قسنطينة",
    is_available: true,
    rating: 4.1,
    trust_score: 74,
    is_premium: false,
    is_verified: false,
    owner_id: 1,
    size_options: ["M", "L", "XL"],
    color_options: ["رمادي", "رمادي غامق"],
  },
];

// ---- Artisans (8 items) ----
export const artisans = [
  {
    id: 1,
    name: "Amira Benmoussa",
    name_ar: "أميرة بن موسى",
    specialty: "Luxury Sewing",
    specialty_ar: "خياطة فاخرة",
    rating: 4.9,
    location: "قسنطينة",
    avatar: "https://picsum.photos/seed/artisan1/200/200",
    bio_ar: "خياطة جزائرية محترفة مع أكثر من 15 سنة خبرة في تصميم وخياطة فساتين الزفاف والأزياء الفاخرة. حائزة على جائزة أفضل مصممة في مهرجان الأزياء الجزائري 2023.",
    is_verified: true,
    trust_score: 96,
    completed_orders: 234,
    specialties: ["فساتين زفاف", "قفطان", "أزياء رسمية"],
    response_time: "خلال ساعتين",
  },
  {
    id: 2,
    name: "Fatima Zohra Hadj",
    name_ar: "فاطمة الزهراء حاج",
    specialty: "Traditional Embroidery",
    specialty_ar: "تطريز تقليدي",
    rating: 5.0,
    location: "تلمسان",
    avatar: "https://picsum.photos/seed/artisan2/200/200",
    bio_ar: "فنانة تطريز من تلمسان، تحمل إرث عائلة من الحرفيين. متخصصة في التطريز التلمساني التقليدي بخيوط الذهب والفضة.",
    is_verified: true,
    trust_score: 98,
    completed_orders: 189,
    specialties: ["تطريز ذهبي", "تطريز تلمساني", "تطريز على الحرير"],
    response_time: "خلال ساعة",
  },
  {
    id: 3,
    name: "Nadia Boudiaf",
    name_ar: "نادية بوزياف",
    specialty: "Fashion Design",
    specialty_ar: "تصميم أزياء",
    rating: 4.8,
    location: "الجزائر العاصمة",
    avatar: "https://picsum.photos/seed/artisan3/200/200",
    bio_ar: "مصممة أزياء جزائرية معروفة، تخرجت من مدرسة الأزياء العليا في باريس. تصمم أزياء تجمع بين الطابع الجزائري والعصرية.",
    is_verified: true,
    trust_score: 94,
    completed_orders: 312,
    specialties: ["تصميم أزياء", "قفطان عصري", "أزياء سهرة"],
    response_time: "خلال 3 ساعات",
  },
  {
    id: 4,
    name: "Samia Khelifi",
    name_ar: "سامية خليفي",
    specialty: "Event Photography",
    specialty_ar: "تصوير مناسبات",
    rating: 4.7,
    location: "وهران",
    avatar: "https://picsum.photos/seed/artisan4/200/200",
    bio_ar: "مصورة محترفة متخصصة في تصوير الأعراس والمناسبات الخاصة. تقدم خدمات تصوير فوتوغرافي وفيديو عالي الجودة.",
    is_verified: true,
    trust_score: 90,
    completed_orders: 456,
    specialties: ["تصوير أعراس", "تصوير فيديو", "تصوير بورتريه"],
    response_time: "خلال ساعة",
  },
  {
    id: 5,
    name: "Leila Mesbah",
    name_ar: "ليلى مصباح",
    specialty: "Professional Makeup",
    specialty_ar: "مكياج احترافي",
    rating: 4.8,
    location: "عنابة",
    avatar: "https://picsum.photos/seed/artisan5/200/200",
    bio_ar: "خبيرة مكياج محترفة مع شهادات دولية. متخصصة في مكياج العروس والحفلات بأساليب عربية وعالمية.",
    is_verified: true,
    trust_score: 92,
    completed_orders: 567,
    specialties: ["مكياج عروس", "مكياج حفلات", "تسريحات شعر"],
    response_time: "خلال 30 دقيقة",
  },
  {
    id: 6,
    name: "Houria Cherif",
    name_ar: "هورية شريف",
    specialty: "Floral Arrangement",
    specialty_ar: "تنسيق زهور",
    rating: 4.6,
    location: "البليدة",
    avatar: "https://picsum.photos/seed/artisan6/200/200",
    bio_ar: "فنانة تنسيق زهور محترفة، تصمم باقات وأرصفة زهور للأعراس والمناسبات بأسلوب فني فريد.",
    is_verified: true,
    trust_score: 87,
    completed_orders: 201,
    specialties: ["باقات زهور", "تنسيق أعراس", "ديكور زهور"],
    response_time: "خلال ساعتين",
  },
  {
    id: 7,
    name: "Djamilia Ait Ahmed",
    name_ar: "جميلة آيت أحمد",
    specialty: "Luxury Sewing & Alterations",
    specialty_ar: "خياطة وتعديل فاخرة",
    rating: 4.5,
    location: "سطيف",
    avatar: "https://picsum.photos/seed/artisan7/200/200",
    bio_ar: "خياطة متخصصة في تعديل وتفصيل الأزياء الفاخرة. تتميز بدقة القياسات والاهتمام بأدق التفاصيل.",
    is_verified: true,
    trust_score: 84,
    completed_orders: 378,
    specialties: ["تعديل أزياء", "تفصيل على المقاس", "إصلاح ملابس فاخرة"],
    response_time: "خلال 4 ساعات",
  },
  {
    id: 8,
    name: "Yasmine Ould Mohand",
    name_ar: "ياسمين ولد محمد",
    specialty: "Caftan & Karstassiya Design",
    specialty_ar: "تصميم قفطان وقرطاسيات",
    rating: 4.9,
    location: "قسنطينة",
    avatar: "https://picsum.photos/seed/artisan8/200/200",
    bio_ar: "مصممة متخصصة في القفطان والقرطاسيات الجزائرية. تحافظ على التقاليد العريقة مع لمسة عصرية مبتكرة.",
    is_verified: true,
    trust_score: 95,
    completed_orders: 267,
    specialties: ["قفطان جزائري", "قرطاسية", "فوقية"],
    response_time: "خلات ساعة واحدة",
  },
];

// ---- Bundles (5 items) ----
export const bundles = [
  {
    id: 1,
    name: "Wedding Complete Bundle",
    name_ar: "باقة زفاف شاملة",
    description_ar: "باقة متكاملة لليوم المميز تشمل فستان زفاف، بدلة العريس، تنسيق الزهور، والمكياج. وفر أكثر من 15% مقارنة بالحجز المنفرد.",
    discount_percentage: 15,
    total_price: 55000,
    products: [1, 8],
    image: "https://picsum.photos/seed/bundle1/600/400",
    includes: ["فستان زفاف أميرة الزهراء", "بدلة زفاف رجالية عاجية", "تنسيق زهور", "مكياج عروس"],
    valid_days: 3,
  },
  {
    id: 2,
    name: "Gala Night Bundle",
    name_ar: "باقة ليلة غالا",
    description_ar: "باقة مثالية للسهرات الراقية وحفلات الغالا. تشمل فستان سهرة أنيق وبدلة رسمية مع خصم خاص.",
    discount_percentage: 12,
    total_price: 16000,
    products: [7, 15],
    image: "https://picsum.photos/seed/bundle2/600/400",
    includes: ["فستان سهرة وردي", "بدلة رسمية كحلية"],
    valid_days: 1,
  },
  {
    id: 3,
    name: "Family Events Bundle",
    name_ar: "باقة مناسبات عائلية",
    description_ar: "باقة للمناسبات العائلية والاحتفالات. تشمل قفطان نسائي وبدلة رجالية مع خصم 10%.",
    discount_percentage: 10,
    total_price: 22000,
    products: [9, 20],
    image: "https://picsum.photos/seed/bundle3/600/400",
    includes: ["قفطان تقليدي أحمر", "بدلة رمادية قصيرة"],
    valid_days: 2,
  },
  {
    id: 4,
    name: "Bridal Caftan Set",
    name_ar: "طقم قفطان العروس",
    description_ar: "طقم كامل للعروس يشمل قفطان ذهبي وقرطاسية مطرّزة. خصم 18% على المجموعة الكاملة.",
    discount_percentage: 18,
    total_price: 30000,
    products: [3, 12],
    image: "https://picsum.photos/seed/bundle4/600/400",
    includes: ["قفطان جزائري ملكي ذهبي", "قرطاسية بخيوط الذهب"],
    valid_days: 3,
  },
  {
    id: 5,
    name: "Traditional Tlemcen Set",
    name_ar: "طقم تلمسان التقليدي",
    description_ar: "طقم تقليدي من تلمسان يشمل قفطان أزرق وجلابية بيضاء. تجربة أصيلة للمناسبات الكبرى.",
    discount_percentage: 14,
    total_price: 31000,
    products: [6, 10],
    image: "https://picsum.photos/seed/bundle5/600/400",
    includes: ["قفطان عروس أزرق ياقوتي", "جلابية ملكية بيضاء"],
    valid_days: 3,
  },
];

// ---- Local Guide Services (12 items) ----
export const localGuideServices = [
  {
    id: 1,
    name: "Dar El Arous Constantine",
    name_ar: "دار العروس - قسنطينة",
    category: "Wedding Venues",
    category_ar: "أماكن أعراس",
    description_ar: "قاعة أعراس فاخرة في قلب قسنطينة تتسع لـ 500 ضيف مع ديكور راقي وخدمات شاملة",
    price_range: "150,000 - 300,000 DA",
    location: "قسنطينة",
    rating: 4.8,
    image: "https://picsum.photos/seed/guide1/600/400",
    is_verified: true,
    contact_phone: "0555 123 456",
  },
  {
    id: 2,
    name: "Studio El Nor Algiers",
    name_ar: "ستوديو النور - الجزائر",
    category: "Photography",
    category_ar: "مصورين",
    description_ar: "استوديو تصوير احترافي متخصص في تصوير الأعراس والمناسبات. فريق مكون من 4 مصورين محترفين",
    price_range: "80,000 - 200,000 DA",
    location: "الجزائر العاصمة",
    rating: 4.9,
    image: "https://picsum.photos/seed/guide2/600/400",
    is_verified: true,
    contact_phone: "0661 789 012",
  },
  {
    id: 3,
    name: "Makeup by Amina",
    name_ar: "مكياج أمينة",
    category: "Makeup Artists",
    category_ar: "مكياج",
    description_ar: "خدمات مكياج احترافي في المنزل أو صالون العروس. استخدام منتجات عالمية عالية الجودة",
    price_range: "15,000 - 35,000 DA",
    location: "وهران",
    rating: 4.7,
    image: "https://picsum.photos/seed/guide3/600/400",
    is_verified: true,
    contact_phone: "0770 345 678",
  },
  {
    id: 4,
    name: "DJ Karim Events",
    name_ar: "دي جي كريم - حفلات",
    category: "DJ Services",
    category_ar: "دج",
    description_ar: "دي جي محترف مع أحدث المعدات الصوتية والإضاءة. يقدم مزيج من الموسيقى الجزائرية والعالمية",
    price_range: "50,000 - 120,000 DA",
    location: "البليدة",
    rating: 4.6,
    image: "https://picsum.photos/seed/guide4/600/400",
    is_verified: true,
    contact_phone: "0542 567 890",
  },
  {
    id: 5,
    name: "Roses d'Or Annaba",
    name_ar: "ورود ذهبية - عنابة",
    category: "Florists",
    category_ar: "زهور",
    description_ar: "محل زهور فاخر يقدم خدمات تنسيق الزهور للأعراس والمناسبات. توصيل مجاني في عنابة",
    price_range: "20,000 - 80,000 DA",
    location: "عنابة",
    rating: 4.5,
    image: "https://picsum.photos/seed/guide5/600/400",
    is_verified: true,
    contact_phone: "0698 234 567",
  },
  {
    id: 6,
    name: "Events Pro Sétif",
    name_ar: "إيفانتس برو - سطيف",
    category: "Event Planning",
    category_ar: "تنسيق حفلات",
    description_ar: "شركة تنسيق حفلات متكاملة. من التخطيط إلى التنفيذ، نقدم كل ما تحتاجه لمناسبتك المثالية",
    price_range: "100,000 - 500,000 DA",
    location: "سطيف",
    rating: 4.8,
    image: "https://picsum.photos/seed/guide6/600/400",
    is_verified: true,
    contact_phone: "0550 678 901",
  },
  {
    id: 7,
    name: "Chef Mourad Catering",
    name_ar: "الشيف مراد - تموين",
    category: "Catering",
    category_ar: "طباخين",
    description_ar: "خدمات تموين احترافية للأعراس والمناسبات. قائمة طعام جزائرية تقليدية وعالمية متنوعة",
    price_range: "800 - 2,500 DA/طبق",
    location: "الجزائر العاصمة",
    rating: 4.9,
    image: "https://picsum.photos/seed/guide7/600/400",
    is_verified: true,
    contact_phone: "0662 890 123",
  },
  {
    id: 8,
    name: "Luxury Cars Oran",
    name_ar: "سيارات فاخرة - وهران",
    category: "Wedding Cars",
    category_ar: "سيارات أعراس",
    description_ar: "تأجير سيارات فاخرة للأعراس. مركبات مرسيدس وبي إم دبليو مع سائق محترف",
    price_range: "30,000 - 80,000 DA",
    location: "وهران",
    rating: 4.4,
    image: "https://picsum.photos/seed/guide8/600/400",
    is_verified: false,
    contact_phone: "0771 901 234",
  },
  {
    id: 9,
    name: "Palais des Fêtes Tlemcen",
    name_ar: "قصر الأفراح - تلمسان",
    category: "Wedding Venues",
    category_ar: "أماكن أعراس",
    description_ar: "قصر أفراح تاريخي في تلمسان بطراز معماري أندلسي. يتسع لـ 300 ضيف مع حديقة خاصة",
    price_range: "100,000 - 250,000 DA",
    location: "تلمسان",
    rating: 4.7,
    image: "https://picsum.photos/seed/guide9/600/400",
    is_verified: true,
    contact_phone: "0543 012 345",
  },
  {
    id: 10,
    name: "Snap Wedding Photography",
    name_ar: "سناب للتصوير",
    category: "Photography",
    category_ar: "مصورين",
    description_ar: "فريق تصوير متخصص في أعراس المغرب العربي. تصوير جوي بالدرون ومعرض صور رقمي",
    price_range: "60,000 - 150,000 DA",
    location: "قسنطينة",
    rating: 4.6,
    image: "https://picsum.photos/seed/guide10/600/400",
    is_verified: true,
    contact_phone: "0664 123 456",
  },
  {
    id: 11,
    name: "Belle Visage Makeup",
    name_ar: "بيل فيساج - مكياج",
    category: "Makeup Artists",
    category_ar: "مكياج",
    description_ar: "صالون مكياج وتجميل نسائي متخصص في مكياج العروس. منتجات ماك وشارلوت تيلبوري",
    price_range: "20,000 - 45,000 DA",
    location: "الجزائر العاصمة",
    rating: 4.8,
    image: "https://picsum.photos/seed/guide11/600/400",
    is_verified: true,
    contact_phone: "0551 234 567",
  },
  {
    id: 12,
    name: "DJ Rachid Sound",
    name_ar: "دي جي رشيد - صوتيات",
    category: "DJ Services",
    category_ar: "دج",
    description_ar: "دي جي مع 10 سنوات خبرة. معدات صوتية احترافية وطبلة جزائرية تقليدية",
    price_range: "40,000 - 100,000 DA",
    location: "عنابة",
    rating: 4.5,
    image: "https://picsum.photos/seed/guide12/600/400",
    is_verified: false,
    contact_phone: "0772 345 678",
  },
];

// ---- Vendors (6 items) ----
export const vendors = [
  {
    id: 1,
    name: "El Ksar Fashion House",
    name_ar: "دار القصر للأزياء",
    description: "A luxury fashion house in Constantine specializing in wedding dresses and traditional Algerian attire. Established in 2010.",
    description_ar: "دار أزياء فاخرة في قسنطينة متخصصة في فساتين الزفاف والأزياء التقليدية الجزائرية. تأسست عام 2010.",
    location: "قسنطينة",
    city: "قسنطينة",
    rating: 4.9,
    trust_score: 96,
    products_count: 45,
    total_sales: 387,
    avatar: "https://picsum.photos/seed/vendor1/200/200",
    logo: "https://picsum.photos/seed/vendor1/200/200",
    is_verified: true,
    joined_date: "2020-03-15",
    website: "https://www.facebook.com/ElKsarFashion",
  },
  {
    id: 2,
    name: "Casbah Couture",
    name_ar: "كوتور القصبة",
    description: "A luxury fashion boutique in the heart of Algiers. Offers the latest fashion trends with an authentic Algerian touch.",
    description_ar: "متجرب للأزياء الفاخرة في قلب العاصمة. يقدم أحدث صيحات الموضة مع لمسة جزائرية أصيلة.",
    location: "الجزائر العاصمة",
    city: "الجزائر العاصمة",
    rating: 4.7,
    trust_score: 92,
    products_count: 62,
    total_sales: 425,
    avatar: "https://picsum.photos/seed/vendor2/200/200",
    logo: "https://picsum.photos/seed/vendor2/200/200",
    is_verified: true,
    joined_date: "2019-07-22",
    website: "https://www.instagram.com/casbahcouture.dz",
  },
  {
    id: 3,
    name: "Tlemcani Heritage",
    name_ar: "تراث تلمساني",
    description: "A shop specializing in traditional Tlemcen attire. Offers the finest handmade caftans and karstassiyat.",
    description_ar: "متجر متخصص في الأزياء التقليدية التلمسانية. يقدم أجود أنواع القفطان والقرطاسيات المصنوعة يدوياً.",
    location: "تلمسان",
    city: "تلمسان",
    rating: 4.8,
    trust_score: 95,
    products_count: 38,
    total_sales: 312,
    avatar: "https://picsum.photos/seed/vendor3/200/200",
    logo: "https://picsum.photos/seed/vendor3/200/200",
    is_verified: true,
    joined_date: "2021-01-10",
    website: "https://www.facebook.com/TlemcaniHeritage",
  },
  {
    id: 4,
    name: "Oran Elegant Wear",
    name_ar: "أناقة وهران",
    description: "An elegant fashion gallery in Oran offering a wide range of premium men's and women's attire.",
    description_ar: "معرض أزياء راقي في وهران يقدم تشكيلة واسعة من الأزياء الراقية للرجال والنساء.",
    location: "وهران",
    city: "وهران",
    rating: 4.5,
    trust_score: 87,
    products_count: 29,
    total_sales: 198,
    avatar: "https://picsum.photos/seed/vendor4/200/200",
    logo: "https://picsum.photos/seed/vendor4/200/200",
    is_verified: true,
    joined_date: "2022-05-18",
    website: "https://www.facebook.com/OranElegantWear",
  },
  {
    id: 5,
    name: "Annaba Bridal Studio",
    name_ar: "ستوديو عروس عنابة",
    description: "A bridal studio in Annaba specializing in wedding dresses. Offers exceptional bridal gowns and custom tailoring services.",
    description_ar: "ستوديو متخصص في أزياء العروسات في عنابة. يقدم فساتين زفاف استثنائية وخدمات تفصيل حسب الطلب.",
    location: "عنابة",
    city: "عنابة",
    rating: 4.6,
    trust_score: 89,
    products_count: 24,
    total_sales: 156,
    avatar: "https://picsum.photos/seed/vendor5/200/200",
    logo: "https://picsum.photos/seed/vendor5/200/200",
    is_verified: false,
    joined_date: "2023-02-28",
    website: "https://www.instagram.com/annababridal",
  },
  {
    id: 6,
    name: "Sétif Fashion Gallery",
    name_ar: "غاليري أزياء سطيف",
    description: "A fashion gallery in Sétif offering a diverse collection of traditional and modern attire at competitive prices.",
    description_ar: "غاليري أزياء في سطيف يقدم تشكيلة متنوعة من الأزياء التقليدية والعصرية بأسعار تنافسية.",
    location: "سطيف",
    city: "سطيف",
    rating: 4.4,
    trust_score: 83,
    products_count: 31,
    total_sales: 142,
    avatar: "https://picsum.photos/seed/vendor6/200/200",
    logo: "https://picsum.photos/seed/vendor6/200/200",
    is_verified: false,
    joined_date: "2023-08-05",
    website: "https://www.facebook.com/SetifFashionGallery",
  },
];

// ---- Reviews (10 items) ----
export const reviews = [
  {
    id: 1,
    booking_id: 101,
    reviewer_id: 10,
    reviewer_name: "سارة بن عبد الله",
    product_id: 1,
    rating: 5,
    comment: "فستان الزفاف كان رائعاً! الجودة ممتازة والتطريز يدوي بامتياز. أنصح بشدة كل عروس بتجربته. الخدمة كانت سريعة والتوصيل في الموعد.",
    is_verified: true,
    created_at: "2024-12-15T14:30:00Z",
  },
  {
    id: 2,
    booking_id: 102,
    reviewer_id: 11,
    reviewer_name: "كريم بوجلال",
    product_id: 2,
    rating: 4,
    comment: "البدلة كانت نظيفة ومكوية بشكل جيد. القماش ذو جودة عالية. فقط أتمنى لو كان هناك خيار لتعديل المقاس.",
    is_verified: true,
    created_at: "2024-12-10T09:15:00Z",
  },
  {
    id: 3,
    booking_id: 103,
    reviewer_id: 12,
    reviewer_name: "نورة بلقاسم",
    product_id: 3,
    rating: 5,
    comment: "القفطان الذهبي كان تحفة فنية! التطريز بالذهب الخالص جعلني أشعر بالملكية. شكراً على التجربة الرائعة.",
    is_verified: true,
    created_at: "2024-11-28T16:45:00Z",
  },
  {
    id: 4,
    booking_id: 104,
    reviewer_id: 13,
    reviewer_name: "ياسين مراد",
    product_id: 6,
    rating: 5,
    comment: "قفطان العروس الأزرق كان أجمل مما تخيلت. زوجتي كانت سعيدة جداً. اللون الأزرق الياقوتي ساحر فعلاً.",
    is_verified: true,
    created_at: "2024-11-20T11:00:00Z",
  },
  {
    id: 5,
    booking_id: 105,
    reviewer_id: 14,
    reviewer_name: "هدى شريف",
    product_id: 4,
    rating: 4,
    comment: "القرطاسية جميلة جداً والتطريز دقيق. لكن التوصيل تأخر يوم واحد عن الموعد المحدد.",
    is_verified: true,
    created_at: "2024-11-15T08:30:00Z",
  },
  {
    id: 6,
    booking_id: 106,
    reviewer_id: 15,
    reviewer_name: "محمد أمين زروال",
    product_id: 8,
    rating: 5,
    comment: "بدلة الزفاف كانت مثالية! القماش فاخر والربطة الحريرية أضافت لمسة راقية. الحجز والاستلام كانا سهلين.",
    is_verified: true,
    created_at: "2024-11-05T13:20:00Z",
  },
  {
    id: 7,
    booking_id: 107,
    reviewer_id: 16,
    reviewer_name: "إيمان حمداني",
    product_id: 14,
    rating: 4,
    comment: "فستان الدانتيل جميل وأنيق. الخامة جيدة لكن كنت أتمنى لو كان الذيل أطول قليلاً.",
    is_verified: false,
    created_at: "2024-10-28T17:45:00Z",
  },
  {
    id: 8,
    booking_id: 108,
    reviewer_id: 17,
    reviewer_name: "بلال بن عمر",
    product_id: 15,
    rating: 4,
    comment: "البدلة الكحلية كانت مناسبة جداً للمناسبة. السعر معقول مقارنة بالجودة المقدمة.",
    is_verified: true,
    created_at: "2024-10-20T10:00:00Z",
  },
  {
    id: 9,
    booking_id: 109,
    reviewer_id: 18,
    reviewer_name: "رنا مهدي",
    product_id: 12,
    rating: 5,
    comment: "القرطاسية بخيوط الذهب كانت مذهلة! التطريز على الحرير يظهر جمال الحرفية الجزائرية. تجربة لا تُنسى.",
    is_verified: true,
    created_at: "2024-10-12T15:30:00Z",
  },
  {
    id: 10,
    booking_id: 110,
    reviewer_id: 19,
    reviewer_name: "عبد الرحمن بن ناصر",
    product_id: 20,
    rating: 4,
    comment: "البدلة الرمادية القصيرة كانت شيك وأنيقة. مناسبة للسهرات. سأحجز مرة أخرى بالتأكيد.",
    is_verified: false,
    created_at: "2024-10-01T12:15:00Z",
  },
];

// ---- FAQs (8 items) ----
export const faqs = [
  {
    id: 1,
    question_ar: "كيف أعمل حجز على المنصة؟",
    answer_ar: "يمكنك حجز أي قطعة بسهولة: اختر المنتج الذي يعجبك، حدد تواريخ الكراء، ثم أكمل عملية الدفع. ستصلك تأكيدات الحجز عبر البريد الإلكتروني والرسائل النصية.",
    category: "حجز",
    order: 1,
  },
  {
    id: 2,
    question_ar: "ما هي شروط الإرجاع؟",
    answer_ar: "يجب إرجاع القطعة في نفس الحالة التي استلمتها بها، نظيفة ومكوية. يجب الإرجاع في الموعد المحدد لتجنب غرامات التأخير. في حالة وجود تلف، يتم احتساب تكلفة الإصلاح من وديعة الضمان.",
    category: "إرجاع",
    order: 2,
  },
  {
    id: 3,
    question_ar: "هل التأمين إلزامي؟",
    answer_ar: "التأمين اختياري لكنه موصى به بشدة. يغطي التأمين الأضرار العرضية التي قد تحدث أثناء فترة الكراء. تكلفة التأمين تتراوح بين 5% و10% من قيمة الكراء.",
    category: "تأمين",
    order: 3,
  },
  {
    id: 4,
    question_ar: "كيف يتم التحقق من هويتي؟",
    answer_ar: "نطلب نسخة من بطاقة التعريف الوطنية أو جواز السفر عند أول حجز. العملية تتم بشكل آمن ومشفر لحماية بياناتك الشخصية.",
    category: "حساب",
    order: 4,
  },
  {
    id: 5,
    question_ar: "ما هي طرق الدفع المتاحة؟",
    answer_ar: "نقبل الدفع عبر بطاقة بريديموب، التحويل البنكي (CCP وBaridimob)، والنقد عند الاستلام. جميع المعاملات محمية بنظام الوداعة الآمن.",
    category: "دفع",
    order: 5,
  },
  {
    id: 6,
    question_ar: "هل يمكنني تعديل أو إلغاء الحجز؟",
    answer_ar: "نعم، يمكنك تعديل أو إلغاء الحجز قبل 48 ساعة من تاريخ الاستلام مجاناً. الإلغاء بعد ذلك قد يترتب عليه رسوم. يمكنك التعديل من صفحة حجوزاتك.",
    category: "حجز",
    order: 6,
  },
  {
    id: 7,
    question_ar: "ما هو نظام الوداعة الآمن؟",
    answer_ar: "نظام الوداعة الآمن يضمن حماية أموالك. لا يتم تحويل المبلغ للبائع إلا بعد استلامك للقطعة وتأكيد جودتها. في حالة نزاع، يتم احتجاز المبلغ حتى حل المشكلة.",
    category: "دفع",
    order: 7,
  },
  {
    id: 8,
    question_ar: "كيف يتم تنظيف الملابس قبل وبعد الكراء؟",
    answer_ar: "جميع الملابس تخضع لعملية تنظيف احترافية وتبخير قبل كل كراء. لدينا معايير صارمة للنظافة والتعقيم لضمان حصولك على قطعة في حالة مثالية.",
    category: "نظافة",
    order: 8,
  },
];

// ---- Blog Posts (4 items) ----
export const blogPosts = [
  {
    id: 1,
    title_ar: "أحدث صيحات أزياء الزفاف في الجزائر 2025",
    slug: "wedding-fashion-trends-algeria-2025",
    excerpt_ar: "اكتشفي أحدث اتجاهات أزياء الزفاف في الجزائر لهذا العام. من القفطان التقليدي إلى الفساتين العصرية.",
    content_ar: "يشهد عالم أزياء الزفاف في الجزائر تطوراً ملحوظاً هذا العام. يأتي القفطان الجزائري في مقدمة الاتجاهات مع إضافات عصرية تجمع بين التراث والحداثة. كما تشهد فساتين الزفاف الغربية طلباً متزايداً مع لمسات شرقية مميزة. من أبرز الصيحات هذا العام: الألوان الزاهية بدلاً من الأبيض التقليدي، التطريز بالألماس المقلّد، والأقمشة المتدلية ذات الأثر الدرامي.",
    image: "https://picsum.photos/seed/blog1/800/400",
    author_ar: "نادية بوزياف",
    published_at: "2024-12-01T10:00:00Z",
    category_ar: "أزياء",
    read_time: "5 دقائق",
  },
  {
    id: 2,
    title_ar: "دليلك الشامل لاختيار القفطان الجزائري المثالي",
    slug: "guide-choosing-perfect-caftan",
    excerpt_ar: "نصائح وإرشادات لاختيار القفطان المناسب لمناسبتك. تعرّفي على أنواع القفطان وكيفية تنسيقه.",
    content_ar: "القفطان الجزائري هو أكثر من مجرد زي تقليدي، إنه رمز للهوية والأناقة. لاختيار القفطان المثالي، يجب مراعاة عدة عوامل: نوع المناسبة، لون البشرة، الميزانية، والذوق الشخصي. أنواع القفطان تشمل: القفطان العادي، القفطان المطرّز، والقفطان الملكي. كل نوع له خصائصه ومناسباته.",
    image: "https://picsum.photos/seed/blog2/800/400",
    author_ar: "ياسمين ولد محمد",
    published_at: "2024-11-15T12:00:00Z",
    category_ar: "إرشادات",
    read_time: "8 دقائق",
  },
  {
    id: 3,
    title_ar: "فن التطريز التلمساني: تراث يعيش",
    slug: "tlemcen-embroidery-heritage",
    excerpt_ar: "رحلة إلى عالم التطريز التلمساني التقليدي. تعرّفي على هذه الحرفة العريقة وكيف تحافظ عليها الأجيال الجديدة.",
    content_ar: "تلمسان، مدينة الفنون والتراث، تُعرف بتطريزها الفريد الذي يُعد من أجمل أشكال الفن الإسلامي. يتميز التطريز التلمساني بخيوط الذهب والفضة على أقمشة الحرير والمخمل. يتطلب كل قطعة أسابيع أو حتى أشهر من العمل الدقيق. اليوم، تسعى مصممات جزائريات شابات لإدخال هذا التراث في عالم الموضة المعاصرة.",
    image: "https://picsum.photos/seed/blog3/800/400",
    author_ar: "فاطمة الزهراء حاج",
    published_at: "2024-11-01T09:00:00Z",
    category_ar: "تراث",
    read_time: "6 دقائق",
  },
  {
    id: 4,
    title_ar: "نصائح لتوفير الميزانية في حفل الزفاف الجزائري",
    slug: "wedding-budget-tips-algeria",
    excerpt_ar: "حيل ذكية لتنظيم حفل زفاف راقي دون إنفاق مبالغ طائلة. من كراء الأزياء إلى تنسيق الحفل.",
    content_ar: "أصبح كراء الأزياء الفاخرة خياراً ذكياً للعديد من الأزواج الجزائريين. بدلاً من شراء فستان زفاف بـ 200,000 دج يستخدم مرة واحدة، يمكنك كراء فستان فاخر بـ 25,000 دج لليوم الواحد. إليك بعض النصائح: احجزي مبكراً للحصول على أفضل الأسعار، استخدمي الباقات المتكاملة التي توفر 15%، واختاري الموسم العادي بدلاً من موسم الأعراس.",
    image: "https://picsum.photos/seed/blog4/800/400",
    author_ar: "أميرة بن موسى",
    published_at: "2024-10-20T11:00:00Z",
    category_ar: "نصائح",
    read_time: "4 دقائق",
  },
];

// ---- Local Guide Categories ----
export const localGuideCategories = [
  { id: 1, name_ar: "أماكن أعراس", slug: "wedding-venues", icon: "🏛️", service_count: 2 },
  { id: 2, name_ar: "مصورين", slug: "photographers", icon: "📷", service_count: 2 },
  { id: 3, name_ar: "مكياج", slug: "makeup", icon: "💄", service_count: 2 },
  { id: 4, name_ar: "دج", slug: "dj", icon: "🎵", service_count: 2 },
  { id: 5, name_ar: "زهور", slug: "florists", icon: "💐", service_count: 1 },
  { id: 6, name_ar: "تنسيق حفلات", slug: "event-planning", icon: "🎉", service_count: 1 },
  { id: 7, name_ar: "طباخين", slug: "catering", icon: "🍽️", service_count: 1 },
  { id: 8, name_ar: "سيارات أعراس", slug: "wedding-cars", icon: "🚗", service_count: 1 },
];

// ---- Helper: Sovereign Response Wrapper ----
export function sovereignResponse<T>(data: T) {
  return {
    status: "sovereign_proceeding" as const,
    code: "RESOLUTION_DELIVERED" as const,
    dignity_preserved: true,
    message_ar: "تمت العملية بنجاح",
    message_en: "Operation successful",
    data,
  };
}