# Generated by Django 5.2.9 on 2026-01-02 08:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artisan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('name_ar', models.CharField(max_length=200, verbose_name='name (Arabic)')),
                ('specialty', models.CharField(choices=[('dress_designer', 'Dress Designer'), ('accessories_designer', 'Accessories Designer'), ('embroidery', 'Embroidery Specialist'), ('beading', 'Beading Specialist'), ('tailor', 'Tailor'), ('other', 'Other')], max_length=30, verbose_name='specialty')),
                ('bio', models.TextField(blank=True, verbose_name='bio')),
                ('bio_ar', models.TextField(blank=True, verbose_name='bio (Arabic)')),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='whatsapp')),
                ('instagram', models.CharField(blank=True, max_length=100, verbose_name='instagram')),
                ('facebook', models.CharField(blank=True, max_length=100, verbose_name='facebook')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('city', models.CharField(default='Constantine', max_length=100, verbose_name='city')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='artisans/profiles/', verbose_name='profile image')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='artisans/covers/', verbose_name='cover image')),
                ('portfolio_description', models.TextField(blank=True, verbose_name='portfolio description')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='rating')),
                ('review_count', models.IntegerField(default=0, verbose_name='review count')),
                ('project_count', models.IntegerField(default=0, verbose_name='project count')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Artisan',
                'verbose_name_plural': 'Artisans',
                'ordering': ['-is_featured', '-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ArtisanPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('title_ar', models.CharField(blank=True, max_length=200, verbose_name='title (Arabic)')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('image', models.ImageField(upload_to='artisans/portfolio/', verbose_name='image')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'Artisan Portfolio',
                'verbose_name_plural': 'Artisan Portfolios',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtisanReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='rating')),
                ('comment', models.TextField(blank=True, verbose_name='comment')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Artisan Review',
                'verbose_name_plural': 'Artisan Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
