# Generated by Django 5.2.9 on 2026-01-02 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artisans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artisan',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artisan_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artisanportfolio',
            name='artisan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='artisans.artisan'),
        ),
        migrations.AddField(
            model_name='artisanreview',
            name='artisan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='artisans.artisan'),
        ),
        migrations.AddField(
            model_name='artisanreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artisan_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='artisan',
            index=models.Index(fields=['specialty', 'is_active'], name='artisans_ar_special_76e099_idx'),
        ),
        migrations.AddIndex(
            model_name='artisan',
            index=models.Index(fields=['city', 'is_active'], name='artisans_ar_city_5eabd2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='artisanreview',
            unique_together={('artisan', 'user')},
        ),
    ]
