# Generated by Django 6.0.1 on 2026-02-02 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artisan',
            options={'ordering': ['-is_featured', '-rating', 'name'], 'verbose_name': 'الحرفي', 'verbose_name_plural': 'الحرفيين'},
        ),
        migrations.AlterModelOptions(
            name='artisanportfolio',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'معرض الحرفي', 'verbose_name_plural': 'معارض الحرفيين'},
        ),
        migrations.AlterModelOptions(
            name='artisanreview',
            options={'ordering': ['-created_at'], 'verbose_name': 'مراجعة الحرفي', 'verbose_name_plural': 'مراجعات الحرفيين'},
        ),
        migrations.AlterField(
            model_name='artisan',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artisan_profile', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='artisanportfolio',
            name='artisan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='artisans.artisan', verbose_name='artisan'),
        ),
        migrations.AlterField(
            model_name='artisanreview',
            name='artisan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='artisans.artisan', verbose_name='artisan'),
        ),
        migrations.AlterField(
            model_name='artisanreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artisan_reviews', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
