# Generated by Django 5.2.9 on 2026-01-02 08:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('name_ar', models.CharField(max_length=100, verbose_name='name (Arabic)')),
                ('material_type', models.CharField(choices=[('box', 'Box'), ('bag', 'Bag'), ('wrap', 'Wrap'), ('bubble_wrap', 'Bubble Wrap'), ('protective_sheet', 'Protective Sheet'), ('hanger', 'Hanger'), ('other', 'Other')], max_length=30, verbose_name='material type')),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cost per unit')),
                ('is_reusable', models.BooleanField(default=False, verbose_name='reusable')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'Packaging Material',
                'verbose_name_plural': 'Packaging Materials',
                'ordering': ['material_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PackagingMaterialUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantity')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='unit cost')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total cost')),
            ],
            options={
                'verbose_name': 'Packaging Material Usage',
                'verbose_name_plural': 'Packaging Material Usages',
            },
        ),
        migrations.CreateModel(
            name='PackagingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_rental_days', models.IntegerField(blank=True, null=True, verbose_name='minimum rental days')),
                ('max_rental_days', models.IntegerField(blank=True, null=True, verbose_name='maximum rental days')),
                ('requires_protection', models.BooleanField(default=False, verbose_name='requires extra protection')),
                ('priority', models.IntegerField(default=0, help_text='Higher priority = selected first', verbose_name='priority')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'Packaging Rule',
                'verbose_name_plural': 'Packaging Rules',
                'ordering': ['-priority', 'packaging_type'],
            },
        ),
        migrations.CreateModel(
            name='PackagingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('name_ar', models.CharField(max_length=100, verbose_name='name (Arabic)')),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('xlarge', 'Extra Large'), ('custom', 'Custom')], max_length=20, verbose_name='size')),
                ('dimensions_length', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='length (cm)')),
                ('dimensions_width', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='width (cm)')),
                ('dimensions_height', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='height (cm)')),
                ('weight_capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='weight capacity (kg)')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'Packaging Type',
                'verbose_name_plural': 'Packaging Types',
                'ordering': ['size', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PackagingInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('prepared', 'Prepared'), ('used', 'In Use'), ('returned', 'Returned'), ('damaged', 'Damaged'), ('disposed', 'Disposed')], default='prepared', max_length=20, verbose_name='status')),
                ('packaging_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='packaging cost')),
                ('prepared_at', models.DateTimeField(auto_now_add=True, verbose_name='prepared at')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='used at')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='returned at')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Packaging Instance',
                'verbose_name_plural': 'Packaging Instances',
                'ordering': ['-prepared_at'],
            },
        ),
    ]
