# Generated by Django 5.2.9 on 2026-01-02 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packaging', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='packaginginstance',
            name='prepared_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_packaging', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='packagingmaterialusage',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packaging.packagingmaterial'),
        ),
        migrations.AddField(
            model_name='packagingmaterialusage',
            name='packaging_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packaging.packaginginstance'),
        ),
        migrations.AddField(
            model_name='packaginginstance',
            name='materials_used',
            field=models.ManyToManyField(related_name='packaging_instances', through='packaging.PackagingMaterialUsage', to='packaging.packagingmaterial'),
        ),
        migrations.AddField(
            model_name='packagingrule',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packaging_rules', to='products.product'),
        ),
        migrations.AddField(
            model_name='packagingrule',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packaging_rules', to='products.category'),
        ),
        migrations.AddField(
            model_name='packagingrule',
            name='packaging_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='packaging.packagingtype'),
        ),
        migrations.AddField(
            model_name='packaginginstance',
            name='packaging_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='packaging.packagingtype'),
        ),
        migrations.AlterUniqueTogether(
            name='packagingmaterialusage',
            unique_together={('packaging_instance', 'material')},
        ),
        migrations.AddIndex(
            model_name='packaginginstance',
            index=models.Index(fields=['booking', 'status'], name='packaging_p_booking_b0334a_idx'),
        ),
    ]
