# Generated by Django 6.0.1 on 2026-02-02 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_options_alter_cart_options_and_more'),
        ('packaging', '0002_initial'),
        ('products', '0003_productvariant_wishlist_alter_category_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packaginginstance',
            options={'ordering': ['-prepared_at'], 'verbose_name': 'مثيل التغليف', 'verbose_name_plural': 'مثيلات التغليف'},
        ),
        migrations.AlterModelOptions(
            name='packagingmaterial',
            options={'ordering': ['material_type', 'name'], 'verbose_name': 'مادة التغليف', 'verbose_name_plural': 'مواد التغليف'},
        ),
        migrations.AlterModelOptions(
            name='packagingmaterialusage',
            options={'verbose_name': 'استخدام مادة التغليف', 'verbose_name_plural': 'استخدامات مواد التغليف'},
        ),
        migrations.AlterModelOptions(
            name='packagingrule',
            options={'ordering': ['-priority', 'packaging_type'], 'verbose_name': 'قاعدة التغليف', 'verbose_name_plural': 'قواعد التغليف'},
        ),
        migrations.AlterModelOptions(
            name='packagingtype',
            options={'ordering': ['size', 'name'], 'verbose_name': 'نوع التغليف', 'verbose_name_plural': 'أنواع التغليف'},
        ),
        migrations.AlterField(
            model_name='packaginginstance',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging', to='bookings.booking', verbose_name='booking'),
        ),
        migrations.AlterField(
            model_name='packaginginstance',
            name='packaging_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='packaging.packagingtype', verbose_name='packaging_type'),
        ),
        migrations.AlterField(
            model_name='packaginginstance',
            name='prepared_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_packaging', to=settings.AUTH_USER_MODEL, verbose_name='prepared_by'),
        ),
        migrations.AlterField(
            model_name='packagingmaterialusage',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packaging.packagingmaterial', verbose_name='material'),
        ),
        migrations.AlterField(
            model_name='packagingmaterialusage',
            name='packaging_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packaging.packaginginstance', verbose_name='packaging_instance'),
        ),
        migrations.AlterField(
            model_name='packagingrule',
            name='packaging_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='packaging.packagingtype', verbose_name='packaging_type'),
        ),
        migrations.AlterField(
            model_name='packagingrule',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packaging_rules', to='products.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='packagingrule',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packaging_rules', to='products.category', verbose_name='product_category'),
        ),
    ]
