# Generated by Django 5.2.9 on 2026-01-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HygieneCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(help_text='Unique certificate number', max_length=50, unique=True, verbose_name='certificate number')),
                ('issued_date', models.DateTimeField(auto_now_add=True, verbose_name='issued date')),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Certificate expiry date if applicable', null=True, verbose_name='expiry date')),
                ('qr_code', models.ImageField(blank=True, help_text='QR code for certificate verification', null=True, upload_to='hygiene_certificates/qr/', verbose_name='QR code')),
                ('is_valid', models.BooleanField(default=True, verbose_name='valid')),
            ],
            options={
                'verbose_name': 'Hygiene Certificate',
                'verbose_name_plural': 'Hygiene Certificates',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='HygieneChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, verbose_name='item name')),
                ('is_checked', models.BooleanField(default=False, verbose_name='checked')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='checked at')),
            ],
            options={
                'verbose_name': 'Hygiene Checklist Item',
                'verbose_name_plural': 'Hygiene Checklist Items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HygieneRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaning_type', models.CharField(choices=[('standard', 'Standard Cleaning'), ('deep', 'Deep Cleaning'), ('sanitization', 'Sanitization'), ('sterilization', 'Sterilization'), ('dry_clean', 'Dry Cleaning')], default='standard', max_length=20, verbose_name='cleaning type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('verified', 'Verified'), ('failed', 'Failed Inspection')], default='pending', max_length=20, verbose_name='status')),
                ('scheduled_date', models.DateTimeField(verbose_name='scheduled date')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verified at')),
                ('cleaning_notes', models.TextField(blank=True, verbose_name='cleaning notes')),
                ('inspection_notes', models.TextField(blank=True, verbose_name='inspection notes')),
                ('chemicals_used', models.TextField(blank=True, help_text='List of cleaning chemicals/products used', verbose_name='chemicals used')),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, help_text='Washing temperature if applicable (°C)', max_digits=5, null=True, verbose_name='temperature')),
                ('passed_inspection', models.BooleanField(default=False, verbose_name='passed inspection')),
                ('quality_score', models.IntegerField(blank=True, help_text='Quality score from 1-10', null=True, verbose_name='quality score')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Hygiene Record',
                'verbose_name_plural': 'Hygiene Records',
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
