# Generated by Django 5.2.9 on 2026-01-02 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hygiene', '0001_initial'),
        ('products', '0001_initial'),
        ('returns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hygienechecklist',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hygienerecord',
            name='cleaned_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaning_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hygienerecord',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hygiene_records', to='products.product'),
        ),
        migrations.AddField(
            model_name='hygienerecord',
            name='related_return',
            field=models.ForeignKey(blank=True, help_text='Return that triggered this cleaning', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hygiene_records', to='returns.return'),
        ),
        migrations.AddField(
            model_name='hygienerecord',
            name='verified_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['admin', 'staff']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_hygiene_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hygienechecklist',
            name='hygiene_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='hygiene.hygienerecord'),
        ),
        migrations.AddField(
            model_name='hygienecertificate',
            name='hygiene_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='hygiene.hygienerecord'),
        ),
        migrations.AddIndex(
            model_name='hygienerecord',
            index=models.Index(fields=['product', 'status'], name='hygiene_hyg_product_cd6327_idx'),
        ),
        migrations.AddIndex(
            model_name='hygienerecord',
            index=models.Index(fields=['scheduled_date', 'status'], name='hygiene_hyg_schedul_24c125_idx'),
        ),
    ]
