# Generated by Django 6.0.1 on 2026-02-02 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hygiene', '0002_initial'),
        ('products', '0003_productvariant_wishlist_alter_category_options_and_more'),
        ('returns', '0003_alter_refund_options_alter_return_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hygienecertificate',
            options={'ordering': ['-issued_date'], 'verbose_name': 'شهادة النظافة', 'verbose_name_plural': 'شهادات النظافة'},
        ),
        migrations.AlterModelOptions(
            name='hygienechecklist',
            options={'ordering': ['id'], 'verbose_name': 'عنصر قائمة النظافة', 'verbose_name_plural': 'عناصر قائمة النظافة'},
        ),
        migrations.AlterModelOptions(
            name='hygienerecord',
            options={'ordering': ['-scheduled_date'], 'verbose_name': 'سجل النظافة', 'verbose_name_plural': 'سجلات النظافة'},
        ),
        migrations.AlterField(
            model_name='hygienecertificate',
            name='hygiene_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='hygiene.hygienerecord', verbose_name='hygiene_record'),
        ),
        migrations.AlterField(
            model_name='hygienechecklist',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='checked_by'),
        ),
        migrations.AlterField(
            model_name='hygienechecklist',
            name='hygiene_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='hygiene.hygienerecord', verbose_name='hygiene_record'),
        ),
        migrations.AlterField(
            model_name='hygienerecord',
            name='cleaned_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaning_records', to=settings.AUTH_USER_MODEL, verbose_name='cleaned_by'),
        ),
        migrations.AlterField(
            model_name='hygienerecord',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hygiene_records', to='products.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='hygienerecord',
            name='related_return',
            field=models.ForeignKey(blank=True, help_text='Return that triggered this cleaning', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hygiene_records', to='returns.return', verbose_name='related_return'),
        ),
        migrations.AlterField(
            model_name='hygienerecord',
            name='verified_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['admin', 'staff']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_hygiene_records', to=settings.AUTH_USER_MODEL, verbose_name='verified_by'),
        ),
    ]
