# Generated by Django 6.0.1 on 2026-02-04 13:52

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='phone number')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified identity')),
                ('trust_score', models.DecimalField(decimal_places=2, default=50.0, max_digits=5, verbose_name='trust score')),
                ('device_fingerprint', models.JSONField(blank=True, default=dict)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='sovereign_user_set', related_query_name='sovereign_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='sovereign_user_set', related_query_name='sovereign_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'sovereign user',
                'verbose_name_plural': 'sovereign users',
            },
        ),
    ]
