# Generated by Django 6.0.1 on 2026-02-04 14:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('vertical_type', models.CharField(choices=[('FASHION', 'Fashion & Events'), ('VEHICLE', 'Vehicles'), ('REAL_ESTATE', 'Real Estate'), ('EQUIPMENT', 'Equipment'), ('GENERIC', 'Other')], default='GENERIC', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('RENTED', 'Rented'), ('MAINTENANCE', 'Maintenance'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='DZD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.CreateModel(
            name='FashionSpec',
            fields=[
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='standard_core.asset')),
                ('size', models.CharField(max_length=10)),
                ('brand', models.CharField(max_length=50)),
                ('material', models.CharField(blank=True, max_length=50)),
                ('color_hex', models.CharField(blank=True, max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='standard_core.user'),
        ),
    ]
