# Generated by Django 6.0.1 on 2026-02-05 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard_core', '0002_asset_alter_user_options_fashionspec_asset_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateSpec',
            fields=[
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='standard_core.asset')),
                ('property_type', models.CharField(default='APARTMENT', max_length=50)),
                ('capacity', models.PositiveIntegerField()),
                ('location_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('has_parking', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleSpec',
            fields=[
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='standard_core.asset')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('transmission', models.CharField(default='MANUAL', max_length=20)),
                ('fuel_type', models.CharField(default='GASOLINE', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='business_mode',
            field=models.CharField(choices=[('PERSONAL', 'Personal (Freelancer)'), ('PROFESSIONAL', 'Professional (Auto-Entrepreneur)')], default='PERSONAL', max_length=20),
        ),
    ]
