# Generated by Django 6.0.1 on 2026-02-05 11:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard_core', '0003_realestatespec_vehiclespec_user_business_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('locked_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('SECURED', 'Secured (Guarantor Active)'), ('ACTIVE', 'Active (Handover)'), ('COMPLETED', 'Completed'), ('DISPUTED', 'Disputed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('smart_agreement_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='standard_core.asset')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings_as_renter', to='standard_core.user')),
            ],
        ),
    ]
