# Generated by Django 6.0.1 on 2026-02-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard_core', '0004_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='locked_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12),
        ),
    ]
