# Generated by Django 6.0.1 on 2026-02-05 11:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard_core', '0005_alter_booking_locked_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='locked_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
