# Generated by Django 6.0.1 on 2026-02-12 16:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard_core', '0006_alter_booking_locked_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_halted', models.BooleanField(default=False, help_text='Emergency Brake. Stops all logic.')),
                ('auto_approve_limit', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=12)),
                ('high_value_threshold', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=12)),
                ('laws', models.JSONField(blank=True, default=dict, help_text='Dynamic configuration keys.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Constitution',
                'verbose_name_plural': 'Constitution',
            },
        ),
    ]
