# Generated by Django 5.2.9 on 2026-01-02 08:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('name_ar', models.CharField(max_length=100, verbose_name='name (Arabic)')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='icon')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LocalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('name_ar', models.CharField(max_length=200, verbose_name='name (Arabic)')),
                ('service_type', models.CharField(choices=[('venue', 'Wedding Venue'), ('photographer', 'Photographer'), ('videographer', 'Videographer'), ('mc', 'MC / Presenter'), ('caterer', 'Caterer'), ('makeup_artist', 'Makeup Artist'), ('hair_stylist', 'Hair Stylist'), ('decorator', 'Decorator'), ('dj', 'DJ'), ('band', 'Band'), ('other', 'Other')], max_length=30, verbose_name='service type')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('description_ar', models.TextField(blank=True, verbose_name='description (Arabic)')),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='whatsapp')),
                ('address', models.TextField(verbose_name='address')),
                ('city', models.CharField(default='Constantine', max_length=100, verbose_name='city')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('price_range_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='min price')),
                ('price_range_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='max price')),
                ('price_note', models.TextField(blank=True, verbose_name='price note')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='local_services/logos/', verbose_name='logo')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='local_services/covers/', verbose_name='cover image')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='rating')),
                ('review_count', models.IntegerField(default=0, verbose_name='review count')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='local_guide.servicecategory')),
            ],
            options={
                'verbose_name': 'Local Service',
                'verbose_name_plural': 'Local Services',
                'ordering': ['-is_featured', '-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='local_services/images/', verbose_name='image')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='alt text')),
                ('is_primary', models.BooleanField(default=False, verbose_name='primary')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='local_guide.localservice')),
            ],
            options={
                'verbose_name': 'Service Image',
                'verbose_name_plural': 'Service Images',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='rating')),
                ('comment', models.TextField(blank=True, verbose_name='comment')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='local_guide.localservice')),
            ],
            options={
                'verbose_name': 'Service Review',
                'verbose_name_plural': 'Service Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
