# Generated by Django 5.2.9 on 2026-01-02 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('local_guide', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicereview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='localservice',
            index=models.Index(fields=['service_type', 'is_active'], name='local_guide_service_f9e6a6_idx'),
        ),
        migrations.AddIndex(
            model_name='localservice',
            index=models.Index(fields=['city', 'is_active'], name='local_guide_city_277288_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='servicereview',
            unique_together={('service', 'user')},
        ),
    ]
