# Generated by Django 6.0.1 on 2026-02-02 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_guide', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localservice',
            options={'ordering': ['-is_featured', '-rating', 'name'], 'verbose_name': 'الخدمة المحلية', 'verbose_name_plural': 'الخدمات المحلية'},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['name'], 'verbose_name': 'فئة الخدمة', 'verbose_name_plural': 'فئات الخدمات'},
        ),
        migrations.AlterModelOptions(
            name='serviceimage',
            options={'ordering': ['order', 'id'], 'verbose_name': 'صورة الخدمة', 'verbose_name_plural': 'صور الخدمات'},
        ),
        migrations.AlterModelOptions(
            name='servicereview',
            options={'ordering': ['-created_at'], 'verbose_name': 'مراجعة الخدمة', 'verbose_name_plural': 'مراجعات الخدمات'},
        ),
        migrations.AlterField(
            model_name='localservice',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='local_guide.servicecategory', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='local_guide.localservice', verbose_name='service'),
        ),
        migrations.AlterField(
            model_name='servicereview',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='local_guide.localservice', verbose_name='service'),
        ),
        migrations.AlterField(
            model_name='servicereview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_reviews', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
