# Generated by Django 6.0.1 on 2026-02-03 04:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_product_is_community_approved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('name_ar', models.CharField(max_length=200, verbose_name='name (Arabic)')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='code')),
                ('address', models.TextField(verbose_name='address')),
                ('city', models.CharField(default='Constantine', max_length=100, verbose_name='city')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='postal code')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('opening_hours', models.JSONField(blank=True, default=dict, help_text='Opening hours by day of week', verbose_name='opening hours')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('manager', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['admin', 'staff']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branches', to=settings.AUTH_USER_MODEL, verbose_name='manager')),
            ],
            options={
                'verbose_name': 'الفرع',
                'verbose_name_plural': 'الفروع',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BranchInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_total', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total quantity')),
                ('quantity_available', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='available quantity')),
                ('quantity_rented', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='rented quantity')),
                ('quantity_maintenance', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='maintenance quantity')),
                ('low_stock_threshold', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='low stock threshold')),
                ('last_restocked', models.DateTimeField(blank=True, null=True, verbose_name='last restocked')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='branches.branch', verbose_name='branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_inventory', to='products.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'مخزون الفرع',
                'verbose_name_plural': 'مخزونات الفروع',
            },
        ),
        migrations.CreateModel(
            name='BranchPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='period start')),
                ('period_end', models.DateField(verbose_name='period end')),
                ('total_bookings', models.IntegerField(default=0, verbose_name='total bookings')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='total revenue')),
                ('total_products', models.IntegerField(default=0, verbose_name='total products')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='average rating')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to='branches.branch', verbose_name='branch')),
            ],
            options={
                'verbose_name': 'أداء الفرع',
                'verbose_name_plural': 'أداءات الفروع',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='BranchStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='staff', max_length=50, verbose_name='role')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='assigned at')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='branches.branch', verbose_name='branch')),
                ('staff', models.ForeignKey(limit_choices_to={'role__in': ['staff', 'admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='branch_assignments', to=settings.AUTH_USER_MODEL, verbose_name='staff')),
            ],
            options={
                'verbose_name': 'موظف الفرع',
                'verbose_name_plural': 'موظفو الفروع',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['is_active', 'city'], name='branches_br_is_acti_62ed31_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['code'], name='branches_br_code_9f8882_idx'),
        ),
        migrations.AddIndex(
            model_name='branchinventory',
            index=models.Index(fields=['branch', 'quantity_available'], name='branches_br_branch__567093_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='branchinventory',
            unique_together={('branch', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='branchperformance',
            unique_together={('branch', 'period_start', 'period_end')},
        ),
        migrations.AlterUniqueTogether(
            name='branchstaff',
            unique_together={('branch', 'staff')},
        ),
    ]
