# Generated by Django 5.2.9 on 2026-01-02 08:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('name_ar', models.CharField(max_length=200, verbose_name='name (Arabic)')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('description', models.TextField(verbose_name='description')),
                ('description_ar', models.TextField(blank=True, verbose_name='description (Arabic)')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Total price of all items separately', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='base price')),
                ('bundle_price', models.DecimalField(decimal_places=2, help_text='Price when purchased as bundle', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='bundle price')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount'), ('free_item', 'Free Item')], default='percentage', max_length=20, verbose_name='discount type')),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, help_text='Discount amount or percentage', max_digits=10, verbose_name='discount value')),
                ('min_days', models.IntegerField(default=1, help_text='Minimum rental days required', validators=[django.core.validators.MinValueValidator(1)], verbose_name='minimum days')),
                ('max_days', models.IntegerField(blank=True, help_text='Maximum rental days (null for unlimited)', null=True, verbose_name='maximum days')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('total_bookings', models.IntegerField(default=0, verbose_name='total bookings')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='rating')),
                ('image', models.ImageField(blank=True, null=True, upload_to='bundles/', verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Bundle',
                'verbose_name_plural': 'Bundles',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BundleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('name_ar', models.CharField(max_length=100, verbose_name='name (Arabic)')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('icon', models.CharField(blank=True, help_text='Icon name or emoji', max_length=50, verbose_name='icon')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'Bundle Category',
                'verbose_name_plural': 'Bundle Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BundleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('product', 'Product'), ('service', 'Service'), ('addon', 'Add-on')], default='product', max_length=20, verbose_name='item type')),
                ('custom_name', models.CharField(blank=True, max_length=200, verbose_name='custom name')),
                ('custom_description', models.TextField(blank=True, verbose_name='custom description')),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='custom price')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantity')),
                ('is_required', models.BooleanField(default=True, help_text='Must be included in bundle', verbose_name='required')),
                ('order', models.IntegerField(default=0, help_text='Display order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'Bundle Item',
                'verbose_name_plural': 'Bundle Items',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BundleReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='rating')),
                ('comment', models.TextField(blank=True, verbose_name='comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Bundle Review',
                'verbose_name_plural': 'Bundle Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BundleBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('total_days', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='total days')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='base price')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='discount amount')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total price')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_use', 'In Use'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bundles.bundle')),
                ('individual_bookings', models.ManyToManyField(blank=True, help_text='Individual product bookings created from this bundle', related_name='bundle_booking', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Bundle Booking',
                'verbose_name_plural': 'Bundle Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
