# Generated by Django 5.2.9 on 2026-01-02 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bundles', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bundlebooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bundle',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bundles', to='bundles.bundlecategory'),
        ),
        migrations.AddField(
            model_name='bundleitem',
            name='bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bundles.bundle'),
        ),
        migrations.AddField(
            model_name='bundleitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bundle_items', to='products.product'),
        ),
        migrations.AddField(
            model_name='bundlereview',
            name='bundle_booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='bundles.bundlebooking'),
        ),
        migrations.AddIndex(
            model_name='bundlebooking',
            index=models.Index(fields=['user', 'status'], name='bundles_bun_user_id_ac4479_idx'),
        ),
        migrations.AddIndex(
            model_name='bundlebooking',
            index=models.Index(fields=['bundle', 'start_date', 'end_date'], name='bundles_bun_bundle__d5223d_idx'),
        ),
        migrations.AddIndex(
            model_name='bundle',
            index=models.Index(fields=['category', 'is_active'], name='bundles_bun_categor_da7905_idx'),
        ),
        migrations.AddIndex(
            model_name='bundle',
            index=models.Index(fields=['is_featured', 'is_active'], name='bundles_bun_is_feat_05ac63_idx'),
        ),
    ]
