# Generated by Django 6.0.1 on 2026-02-02 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundles', '0002_initial'),
        ('products', '0003_productvariant_wishlist_alter_category_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bundle',
            options={'ordering': ['-is_featured', '-created_at'], 'verbose_name': 'الحزمة', 'verbose_name_plural': 'الحزم'},
        ),
        migrations.AlterModelOptions(
            name='bundlebooking',
            options={'ordering': ['-created_at'], 'verbose_name': 'حجز الحزمة', 'verbose_name_plural': 'حجوزات الحزم'},
        ),
        migrations.AlterModelOptions(
            name='bundlecategory',
            options={'ordering': ['name'], 'verbose_name': 'فئة الحزمة', 'verbose_name_plural': 'فئات الحزم'},
        ),
        migrations.AlterModelOptions(
            name='bundleitem',
            options={'ordering': ['order', 'id'], 'verbose_name': 'عنصر الحزمة', 'verbose_name_plural': 'عناصر الحزم'},
        ),
        migrations.AlterModelOptions(
            name='bundlereview',
            options={'ordering': ['-created_at'], 'verbose_name': 'مراجعة الحزمة', 'verbose_name_plural': 'مراجعات الحزم'},
        ),
        migrations.AlterField(
            model_name='bundle',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bundles', to='bundles.bundlecategory', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='bundlebooking',
            name='bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bundles.bundle', verbose_name='bundle'),
        ),
        migrations.AlterField(
            model_name='bundlebooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_bookings', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='bundleitem',
            name='bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bundles.bundle', verbose_name='bundle'),
        ),
        migrations.AlterField(
            model_name='bundleitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bundle_items', to='products.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='bundlereview',
            name='bundle_booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='bundles.bundlebooking', verbose_name='bundle_booking'),
        ),
    ]
