# Generated by Django 5.2.9 on 2026-01-02 08:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Address label (e.g., Home, Office)', max_length=50, verbose_name='label')),
                ('full_address', models.TextField(verbose_name='full address')),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='street')),
                ('city', models.CharField(default='Constantine', max_length=100, verbose_name='city')),
                ('state', models.CharField(blank=True, default='Constantine', max_length=100, verbose_name='state')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='postal code')),
                ('country', models.CharField(default='Algeria', max_length=100, verbose_name='country')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='longitude')),
                ('google_place_id', models.CharField(blank=True, help_text='Google Maps Place ID for this address', max_length=255, verbose_name='Google Place ID')),
                ('is_default', models.BooleanField(default=False, verbose_name='default')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.CharField(choices=[('delivery', 'Delivery'), ('pickup', 'Pickup'), ('both', 'Both Delivery and Pickup')], default='both', max_length=20, verbose_name='delivery type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status')),
                ('delivery_date', models.DateField(verbose_name='delivery date')),
                ('delivery_time_slot', models.CharField(blank=True, help_text='Preferred time slot (e.g., Morning, Afternoon, Evening)', max_length=50, verbose_name='delivery time slot')),
                ('pickup_date', models.DateField(blank=True, null=True, verbose_name='pickup date')),
                ('pickup_time_slot', models.CharField(blank=True, max_length=50, verbose_name='pickup time slot')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='delivery fee')),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='current latitude')),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='current longitude')),
                ('last_tracking_update', models.DateTimeField(blank=True, null=True, verbose_name='last tracking update')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Delivery Request',
                'verbose_name_plural': 'Delivery Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='longitude')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('status', models.CharField(blank=True, help_text='Status at this tracking point', max_length=50, verbose_name='status')),
            ],
            options={
                'verbose_name': 'Delivery Tracking',
                'verbose_name_plural': 'Delivery Tracking',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('name_ar', models.CharField(max_length=100, verbose_name='name (Arabic)')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('city', models.CharField(default='Constantine', max_length=100, verbose_name='city')),
                ('center_latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='center latitude')),
                ('center_longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='center longitude')),
                ('radius_km', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='radius (km)')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='delivery fee')),
                ('same_day_delivery_available', models.BooleanField(default=False, help_text='Whether same-day delivery is available in this zone', verbose_name='same day delivery available')),
                ('same_day_delivery_fee', models.DecimalField(decimal_places=2, default=0, help_text='Additional fee for same-day delivery', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='same day delivery fee')),
                ('same_day_cutoff_time', models.TimeField(blank=True, help_text='Last time to place order for same-day delivery (e.g., 14:00)', null=True, verbose_name='same day cutoff time')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'Delivery Zone',
                'verbose_name_plural': 'Delivery Zones',
                'ordering': ['name'],
            },
        ),
    ]
