# Generated by Django 5.2.9 on 2026-01-02 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_request', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='delivery_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_requests', to='locations.address'),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='pickup_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_requests', to='locations.address'),
        ),
        migrations.AddField(
            model_name='deliverytracking',
            name='delivery_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_history', to='locations.deliveryrequest'),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='delivery_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.deliveryzone'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['user', 'is_default'], name='locations_a_user_id_fce2a5_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['latitude', 'longitude'], name='locations_a_latitud_0fc3d0_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverytracking',
            index=models.Index(fields=['delivery_request', 'timestamp'], name='locations_d_deliver_cdb498_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryrequest',
            index=models.Index(fields=['status', 'delivery_date'], name='locations_d_status_8dbe24_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryrequest',
            index=models.Index(fields=['assigned_driver', 'status'], name='locations_d_assigne_c88e40_idx'),
        ),
    ]
