# Generated by Django 6.0.1 on 2026-02-02 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_options_alter_cart_options_and_more'),
        ('locations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-is_default', '-created_at'], 'verbose_name': 'العنوان', 'verbose_name_plural': 'العناوين'},
        ),
        migrations.AlterModelOptions(
            name='deliveryrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'طلب التوصيل', 'verbose_name_plural': 'طلبات التوصيل'},
        ),
        migrations.AlterModelOptions(
            name='deliverytracking',
            options={'ordering': ['-timestamp'], 'verbose_name': 'تتبع التوصيل', 'verbose_name_plural': 'تتبع التوصيلات'},
        ),
        migrations.AlterModelOptions(
            name='deliveryzone',
            options={'ordering': ['name'], 'verbose_name': 'منطقة التوصيل', 'verbose_name_plural': 'مناطق التوصيل'},
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_assignments', to=settings.AUTH_USER_MODEL, verbose_name='assigned_driver'),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_request', to='bookings.booking', verbose_name='booking'),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='delivery_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_requests', to='locations.address', verbose_name='delivery_address'),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='delivery_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.deliveryzone', verbose_name='delivery_zone'),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='pickup_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_requests', to='locations.address', verbose_name='pickup_address'),
        ),
        migrations.AlterField(
            model_name='deliverytracking',
            name='delivery_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_history', to='locations.deliveryrequest', verbose_name='delivery_request'),
        ),
    ]
