# Generated by Django 5.2.9 on 2026-02-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_wallet_escrowhold_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentwebhook',
            name='event_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Gateway event ID for idempotency protection', max_length=150, null=True, unique=True, verbose_name='event ID'),
        ),
        migrations.AddConstraint(
            model_name='paymentwebhook',
            constraint=models.UniqueConstraint(fields=('payment_method', 'event_id'), name='unique_webhook_event'),
        ),
    ]
