# Generated by Django 5.2.9 on 2026-02-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_verticalreadinessaudit'),
        ('payments', '0003_add_webhook_idempotency'),
    ]

    def migrate_status_to_state(apps, schema_editor):
        EscrowHold = apps.get_model('payments', 'EscrowHold')
        for hold in EscrowHold.objects.all():
            if hold.status == 'held':
                hold.state = 'held'
            elif hold.status == 'released':
                hold.state = 'released'
            elif hold.status == 'refunded':
                hold.state = 'refunded'
            elif hold.status == 'disputed':
                hold.state = 'disputed'
            else:
                hold.state = 'pending'
            hold.save(update_fields=['state'])

    operations = [
        migrations.AddField(
            model_name='escrowhold',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('held', 'Held'), ('released', 'Released'), ('refunded', 'Refunded'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.RunPython(migrate_status_to_state),
        migrations.AlterField(
            model_name='paymentwebhook',
            name='event_id',
            field=models.CharField(db_index=True, default='legacy_event', help_text='Gateway event ID for idempotency protection', max_length=150, unique=True, verbose_name='event ID'),
        ),
        migrations.AddConstraint(
            model_name='escrowhold',
            constraint=models.UniqueConstraint(fields=('booking',), name='unique_escrow_per_booking'),
        ),
    ]
