# Generated by Django 6.0.3 on 2026-03-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_escrowhold_state_alter_paymentwebhook_event_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrowhold',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('held', 'Held'), ('released', 'Released'), ('refunded', 'Refunded'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled'), ('split_released', 'Split Released')], db_index=True, default='pending', max_length=20),
        ),
    ]
