# Generated by Django 5.1.2 on 2026-04-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_gap_03_05_payment_expanded'),
    ]

    operations = []
