# Generated by Django 5.1.2 on 2026-04-01 08:09

import apps.core.crypto.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_remove_wallettransaction_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaridiMobTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', apps.core.crypto.fields.EncryptedCharField(help_text='Encrypted phone number used for BaridiMob payment (AES-256)', max_length=20, verbose_name='phone number')),
                ('external_reference', models.CharField(blank=True, db_index=True, max_length=150, verbose_name='external reference')),
                ('status', models.CharField(choices=[('initiated', 'Initiated (OTP Pending)'), ('pending', 'Pending Gateway Confirmation'), ('success', 'Success ✅'), ('failed', 'Failed ❌'), ('expired', 'Expired 🕒')], default='initiated', max_length=20, verbose_name='status')),
                ('gateway_metadata', models.JSONField(blank=True, default=dict, verbose_name='gateway metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='baridimob_details', to='payments.payment', verbose_name='payment')),
            ],
            options={
                'verbose_name': 'BaridiMob تفاصيل',
                'verbose_name_plural': 'BaridiMob تفاصيل',
                'ordering': ['-created_at'],
            },
        ),
    ]
