# Generated by Django 5.1.2 on 2026-04-06 18:59

import apps.core.crypto.fields
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_adjust_webhook_eventid_uniqueness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrowhold',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='escrowhold',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('held', 'Held'), ('released', 'Released'), ('refunded', 'Refunded'), ('disputed', 'Disputed')], db_column='_legacy_status', default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='otp_code',
            field=apps.core.crypto.fields.EncryptedCharField(blank=True, max_length=10, verbose_name='OTP code'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='phone_number',
            field=apps.core.crypto.fields.EncryptedCharField(blank=True, max_length=20, verbose_name='phone number'),
        ),
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('reference_id__isnull', False), models.Q(('reference_id', ''), _negated=True)), fields=('wallet', 'reference_id', 'transaction_type'), name='unique_wallet_transaction_reference'),
        ),
    ]
