# Generated by Django 5.2.9 on 2026-01-02 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='key')),
                ('value', models.TextField(verbose_name='value')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Chatbot Configuration',
                'verbose_name_plural': 'Chatbot Configurations',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20, verbose_name='role')),
                ('content', models.TextField(verbose_name='content')),
                ('model_used', models.CharField(blank=True, help_text='AI model version used (e.g., gpt-4, gpt-3.5-turbo)', max_length=50, verbose_name='AI model used')),
                ('tokens_used', models.IntegerField(blank=True, help_text='Number of tokens consumed', null=True, verbose_name='tokens used')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional message metadata', verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Unique session identifier', max_length=100, unique=True, verbose_name='session ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('escalated', 'Escalated to Human'), ('closed', 'Closed')], default='active', max_length=20, verbose_name='status')),
                ('language', models.CharField(choices=[('ar', 'العربية'), ('fr', 'Français'), ('en', 'English')], default='ar', max_length=10, verbose_name='language')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='started at')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolved at')),
                ('escalated_at', models.DateTimeField(blank=True, null=True, verbose_name='escalated at')),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Additional context about the conversation', verbose_name='context data')),
            ],
            options={
                'verbose_name': 'Chat Session',
                'verbose_name_plural': 'Chat Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent_type', models.CharField(choices=[('product_inquiry', 'Product Inquiry'), ('booking_help', 'Booking Help'), ('return_inquiry', 'Return Inquiry'), ('delivery_status', 'Delivery Status'), ('pricing', 'Pricing'), ('general_info', 'General Information'), ('complaint', 'Complaint'), ('compliment', 'Compliment'), ('other', 'Other')], max_length=50, verbose_name='intent type')),
                ('confidence', models.DecimalField(decimal_places=4, help_text='Confidence score (0-1)', max_digits=5, verbose_name='confidence')),
                ('extracted_entities', models.JSONField(blank=True, default=dict, help_text='Extracted entities from the message', verbose_name='extracted entities')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intents', to='chatbot.chatmessage')),
            ],
            options={
                'verbose_name': 'Chat Intent',
                'verbose_name_plural': 'Chat Intents',
                'ordering': ['-confidence', '-created_at'],
            },
        ),
    ]
