# Generated by Django 6.0.1 on 2026-02-02 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatbotconfiguration',
            options={'verbose_name': 'إعدادات الدردشة الآلية', 'verbose_name_plural': 'إعدادات الدردشة الآلية'},
        ),
        migrations.AlterModelOptions(
            name='chatintent',
            options={'ordering': ['-confidence', '-created_at'], 'verbose_name': 'نية الدردشة', 'verbose_name_plural': 'نيات الدردشة'},
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'رسالة الدردشة', 'verbose_name_plural': 'رسائل الدردشة'},
        ),
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ['-started_at'], 'verbose_name': 'جلسة الدردشة', 'verbose_name_plural': 'جلسات الدردشة'},
        ),
        migrations.AlterField(
            model_name='chatintent',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intents', to='chatbot.chatmessage', verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='chatintent',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intents', to='chatbot.chatsession', verbose_name='session'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession', verbose_name='session'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='escalated_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['admin', 'staff']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_chats', to=settings.AUTH_USER_MODEL, verbose_name='escalated_to'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
