# Generated by Django 6.0.1 on 2026-02-03 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='agreements/audio/')),
                ('transcript', models.TextField(blank=True, help_text='Whisper transcription')),
                ('extracted_terms', models.JSONField(default=dict, help_text='GPT-4 extracted JSON (price, duration, etc.)')),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('DISPUTED', 'Disputed')], default='PENDING_REVIEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('risk_score_snapshot', models.IntegerField(default=0, help_text='Risk score at time of agreement')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_agreements', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_agreements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'اتفاق ذكي',
                'verbose_name_plural': 'اتفاقيات ذكية',
                'ordering': ['-created_at'],
            },
        ),
    ]
