# Generated by Django 6.0.1 on 2026-02-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartagreement',
            name='buyer_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartagreement',
            name='digital_signature_hash',
            field=models.CharField(blank=True, help_text='SHA-256 of State+Transcript', max_length=64),
        ),
        migrations.AddField(
            model_name='smartagreement',
            name='seller_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
