# Generated by Django 6.0.1 on 2026-02-03 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_idempotency_key'),
        ('contracts', '0002_smartagreement_buyer_signed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', models.JSONField(help_text='Frozen copy of Renter, Owner, Product, and Terms at moment of booking.', verbose_name='agreement snapshot')),
                ('contract_hash', models.CharField(help_text='SHA-256 hash of the snapshot for integrity verification.', max_length=64, verbose_name='digital signature')),
                ('version', models.CharField(default='1.0', max_length=10, verbose_name='contract version')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='bookings.booking', verbose_name='booking')),
            ],
            options={
                'verbose_name': 'العقد الذكي',
                'verbose_name_plural': 'العقود الذكية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='SmartAgreement',
        ),
    ]
