# Generated by Django 5.2.9 on 2026-02-18 12:54

from django.db import migrations, models


def set_legacy_status(apps, schema_editor):
    Contract = apps.get_model("contracts", "Contract")
    # Use update() for bulk efficiency
    Contract.objects.all().update(
        status="legacy",
        signed_at=None
    )


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0011_booking_security_deposit"),
        ("contracts", "0003_contract_delete_smartagreement"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="signed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="signed at"),
        ),
        migrations.AddField(
            model_name="contract",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("signed", "Signed"),
                    ("void", "Void"),
                    ("legacy", "Legacy (Pre-Phase15)"),
                ],
                db_index=True,
                default="draft",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
        migrations.RunPython(set_legacy_status, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="contract",
            name="contract_hash",
            field=models.CharField(
                help_text="SHA-256 hash of the snapshot for integrity verification.",
                max_length=64,
                unique=True,
                verbose_name="digital signature",
            ),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["created_at"], name="contracts_c_created_526229_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["booking"], name="contracts_c_booking_877f06_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["booking", "status"], name="contracts_c_booking_8051df_idx"
            ),
        ),
    ]
