# Generated by Django 6.0.3 on 2026-03-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_contract_signed_at_contract_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_finalized',
            field=models.BooleanField(default=False, help_text='True when both parties have signed. Locks the contract purely.', verbose_name='Is Finalized?'),
        ),
        migrations.AddField(
            model_name='contract',
            name='owner_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Owner IP'),
        ),
        migrations.AddField(
            model_name='contract',
            name='owner_signature',
            field=models.CharField(blank=True, max_length=128, verbose_name='Owner Signature'),
        ),
        migrations.AddField(
            model_name='contract',
            name='owner_signed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Owner Signed At'),
        ),
        migrations.AddField(
            model_name='contract',
            name='renter_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Renter IP'),
        ),
        migrations.AddField(
            model_name='contract',
            name='renter_signature',
            field=models.CharField(blank=True, max_length=128, verbose_name='Renter Signature'),
        ),
        migrations.AddField(
            model_name='contract',
            name='renter_signed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Renter Signed At'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='completed at'),
        ),
    ]
