# Generated by Django 6.0.1 on 2026-02-02 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_add_xxxl_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., "Size M - Red"', max_length=100, verbose_name='name')),
                ('size', models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=10, verbose_name='size')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='color')),
                ('color_hex', models.CharField(blank=True, max_length=7, verbose_name='color hex')),
                ('style', models.CharField(blank=True, max_length=50, verbose_name='style')),
                ('sku', models.CharField(blank=True, max_length=100, unique=True, verbose_name='SKU')),
                ('price_per_day', models.DecimalField(blank=True, decimal_places=2, help_text='Override product price if set', max_digits=10, null=True, verbose_name='price per day')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'متغير المنتج',
                'verbose_name_plural': 'متغيرات المنتجات',
                'ordering': ['size', 'color'],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'عنصر قائمة الأمنيات',
                'verbose_name_plural': 'عناصر قائمة الأمنيات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'الفئة', 'verbose_name_plural': 'الفئات'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'المنتج', 'verbose_name_plural': 'المنتجات'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'صورة المنتج', 'verbose_name_plural': 'صور المنتجات'},
        ),
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_products', to=settings.AUTH_USER_MODEL, verbose_name='المالك'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='product'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name', 'name_ar'], name='products_pr_name_2903af_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price_per_day', 'status'], name='products_pr_price_p_c203cb_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['rating', 'total_rentals'], name='products_pr_rating_d45281_idx'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='products.product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'is_active'], name='products_pr_product_66459e_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['sku'], name='products_pr_sku_dcab68_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'size', 'color', 'style')},
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['user', 'created_at'], name='products_wi_user_id_ae095a_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['product'], name='products_wi_product_4c3cee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'product')},
        ),
    ]
