# Generated by Django 6.0.1 on 2026-02-03 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productvariant_wishlist_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_community_approved',
            field=models.BooleanField(default=False, verbose_name='community approved'),
        ),
    ]
