# Generated by Django 6.0.1 on 2026-02-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_commune_product_delivery_policy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='wilaya',
            field=models.IntegerField(blank=True, choices=[(1, '01 - Adrar'), (2, '02 - Chlef'), (3, '03 - Laghouat'), (4, '04 - Oum El Bouaghi'), (5, '05 - Batna'), (6, '06 - Béjaïa'), (7, '07 - Biskra'), (8, '08 - Béchar'), (9, '09 - Blida'), (10, '10 - Bouira'), (11, '11 - Tamanrasset'), (12, '12 - Tébessa'), (13, '13 - Tlemcen'), (14, '14 - Tiaret'), (15, '15 - Tizi Ouzou'), (16, '16 - Alger'), (17, '17 - Djelfa'), (18, '18 - Jijel'), (19, '19 - Sétif'), (20, '20 - Saïda'), (21, '21 - Skikda'), (22, '22 - Sidi Bel Abbès'), (23, '23 - Annaba'), (24, '24 - Guelma'), (25, '25 - Constantine'), (26, '26 - Médéa'), (27, '27 - Mostaganem'), (28, "28 - M'Sila"), (29, '29 - Mascara'), (30, '30 - Ouargla'), (31, '31 - Oran'), (32, '32 - El Bayadh'), (33, '33 - Illizi'), (34, '34 - Bordj Bou Arreridj'), (35, '35 - Boumerdès'), (36, '36 - El Tarf'), (37, '37 - Tindouf'), (38, '38 - Tissemsilt'), (39, '39 - El Oued'), (40, '40 - Khenchela'), (41, '41 - Souk Ahras'), (42, '42 - Tipaza'), (43, '43 - Mila'), (44, '44 - Aïn Defla'), (45, '45 - Naâma'), (46, '46 - Aïn Témouchent'), (47, '47 - Ghardaïa'), (48, '48 - Relizane'), (49, '49 - Timimoun'), (50, '50 - Bordj Badji Mokhtar'), (51, '51 - Ouled Djellal'), (52, '52 - Béni Abbès'), (53, '53 - In Salah'), (54, '54 - In Guezzam'), (55, '55 - Touggourt'), (56, '56 - Djanet'), (57, "57 - El M'Ghair"), (58, '58 - El Meniaa'), (59, '59 - Wilaya 59 (Expansion)'), (60, '60 - Wilaya 60 (Expansion)'), (61, '61 - Wilaya 61 (Expansion)'), (62, '62 - Wilaya 62 (Expansion)'), (63, '63 - Wilaya 63 (Expansion)'), (64, '64 - Wilaya 64 (Expansion)'), (65, '65 - Wilaya 65 (Expansion)'), (66, '66 - Wilaya 66 (Expansion)'), (67, '67 - Wilaya 67 (Expansion)'), (68, '68 - Wilaya 68 (Expansion)'), (69, '69 - Wilaya 69 (Expansion)')], null=True, verbose_name='Wilaya'),
        ),
    ]
