# Generated by Django 6.0.1 on 2026-02-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_wilaya'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_options',
            field=models.JSONField(blank=True, default=dict, help_text='Structured delivery settings (pickup, zones, costs)', verbose_name='Delivery Options'),
        ),
    ]
