# Generated by Django 6.0.1 on 2026-02-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_delivery_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('maintenance', 'Under Maintenance'), ('unavailable', 'Unavailable'), ('coming_soon', 'Coming Soon')], default='available', max_length=20, verbose_name='status'),
        ),
    ]
