# Generated by Django 6.0.1 on 2026-02-03 14:18

from django.db import migrations
from django.conf import settings

def assign_default_owner(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    User = apps.get_model('users', 'User')  # Assuming 'users' app label
    
    # Try to find a superuser or create a default platform admin
    admin_user = User.objects.filter(is_superuser=True).first()
    if not admin_user:
        # If no superuser exists, create one (Password should be reset later)
        # Note: In a migration, we should be careful creating users. 
        # Better to fallback to the first user if any exists.
        admin_user = User.objects.first()
        
    if not admin_user:
        # If absolutely no users, we can't assign ownership. 
        # This implies DB is empty, so we are safe.
        return

    # Update all products without owner
    Product.objects.filter(owner__isnull=True).update(owner=admin_user)

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_status'),
    ]

    operations = [
        migrations.RunPython(assign_default_owner),
    ]
