# Generated by Django 5.1.2 on 2026-04-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_owner_not_null'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['price_per_day'], name='products_pr_price_p_7b4234_idx'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'size', 'color', 'style'), name='unique_variant_per_product'),
        ),
    ]
