# Generated by Django 5.1.2 on 2026-04-06 18:59

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_owner_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='price per day'),
        ),
    ]
