# Generated by Django 6.0.1 on 2026-02-03 14:37

from django.db import connection, migrations
import os

def apply_rls(apps, schema_editor):
    print("⚠️ SKIPPING RLS (Supabase) to persist local development.")
    return


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(apply_rls),
    ]

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(apply_rls),
    ]
